### ISSUE TITLE
`graphQLErrors` property passed to `onError` is sometimes an empty string

### ISSUE THREAD

**Issue by 6XGate** [apollographql/apollo-client#10590]
### Issue Description

The type definitions for the `onError` link shows that `graphQLErrors` should always be an array of errors. Unfortunately when some servers return a 500 error, it will be an empty string.

### Link to Reproduction

See repro steps

Currently I have to use the following code to prevent this from happening
```
onError(({ networkError }) => {
  if (networkError != null && 'result' in networkError && typeof networkError.result !== 'object') {
    networkError.result = { }
  }
})
```

### Reproduction Steps

It is difficult to create a reproduction case with the given templates. Though I can if needed. But, the offending code is in at [/src/link/error/index.ts:63](https://github.com/apollographql/apollo-client/blob/52a9c8ea1ac08ee53fe1ddbd4ded899ea00a1f9f/src/link/error/index.ts#L63) and may be a lack response parsing sanity checking or sanitation earlier on. It may also be that using a chaining of `&&` should be replaced with something that ensures the networkError result is an object and not something else.

**Comment by hichemBAALI** [comment]
Any update here. I am still having the `graphQLErrors` when authLink fails (token expires). Please let me know if anyone faced the same issue

**Comment by 6XGate** [comment]
> Any update here. I am still having the `graphQLErrors: undefined` when authLink fails (token expires). Please let me know if anyone faced the same issue

That would likely come in as `networkError` if the error is indicate via an HTTP status code like 401 or 403. AFAIK, getting those will results in an undefined `graphQLErrors` value.

**Comment by jerelmiller** [comment]
@6XGate this definitely seems like a bug, good catch! We should absolutely make sure that `graphqlErrors` never get set as an empty string in the event the server response is empty.

Would you be open to submitting a PR to get this fixed? I'd be more than happy to review it.

**Comment by 6XGate** [comment]
Can if I get a chance.

**Comment by euc-callum** [comment]
We're also seeing this for 502 errors 👍

**Comment by fe-jcorreia** [comment]
This issue was fixed for new versions?

**Comment by jerelmiller** [comment]
@fe-jcorreia nope this is still an issue. I'm just realizing though that we have #11329 open to address this. We'll see if we can get a review on that one soon. Thanks for the nudge.

**Comment by Tadimsky** [comment]
I just ran into this issue for our product, causing us to not handle the errors properly and silently fail.
It was for a `405` error response from our reverse proxy, we had just an empty string:
![image](https://github.com/apollographql/apollo-client/assets/1149244/f7db2ddf-6aa8-4d94-8845-ddc21de13146)


Is there a chance we can get this PR merged at some point? @jerelmiller

**Comment by jerelmiller** [comment]
@Tadimsky gah thanks for the reminder. I've had a tab open to review it for a while and it kept slipping my mind. Just reviewed the PR that fixes this and will get it in the next patch release which should go out later this afternoon.
