### ISSUE TITLE
Race-condition in refetchQueries (cache-first query completes before network-only query)

### ISSUE THREAD

**Issue by ctavan** [apollographql/apollo-client#1821]
**Intended outcome:**

Using `refetchQueries` on a mutation should guarantee to update the store from the network query result.

**Actual outcome:**

If the application triggers the same query, that was supposed to be refetched, shortly after the mutation has run (which by default will happen with the `cache-first` policy), this query will typically hit the cache and complete before the `network-only` query issued by `refetchQueries` will finish.

Since the refetch query has a lower `requestId` its result will not be propagated to the store, see: https://github.com/apollographql/apollo-client/blob/d420cbdbb3e6637ee2e8e8c211e3d28850b93c6e/src/queries/store.ts#L135

**How to reproduce the issue:**

See: https://github.com/ctavan/react-apollo-error-template/tree/reproduce-refetch-query-race

I think the issue is best explained when looking at the demo app / screenshot:

<img width="1106" alt="screenshot 2017-06-23 15 47 25" src="https://user-images.githubusercontent.com/508118/27484940-4de63566-582b-11e7-9d0b-1d2443d25ba3.png">

The steps to reproduce are:

1. Load the page -> List query is run and populates the store with 3 people.
2. Go to "create" which unmounts the List and mounts the Create component. Clicking the button will fire a mutation which adds a new person.
3. The mutation has [`refetchQueries: ['People'],` specified](https://github.com/ctavan/react-apollo-error-template/blob/reproduce-refetch-query-race/src/Create.js#L39).
  * As is visible from the console output which simulates the server behavior, apollo-client starts a network request to refetch the query right after the mutation network request has resolved (and even before the `mutate()` promise resolves, as indicated by `Mutation done`). In the example this gets `lastRequestId = 4`:

<img width="1106" alt="screenshot 2017-06-23 16 02 50" src="https://user-images.githubusercontent.com/508118/27485569-8d9201f2-582d-11e7-9ed3-0673a997a654.png">

  * At this point the success callback of the resolved mutation redirects back to the `List` component which re-triggers the list-query there, `lastRequestId = 5`:

<img width="1106" alt="screenshot 2017-06-23 16 04 48" src="https://user-images.githubusercontent.com/508118/27485612-b4b623a8-582d-11e7-8871-f9e30b69c857.png">

  * Shortly after that,  the network request for the refetch resolves and as can be seen from the server output there were actually 4 elements returned.
  * However the store still only holds 3 elements for the `people` query as can be seen from the Apollo client dev toolbar. I assume this is because the `cache-first` which was executed synchronously resolved before the `network-only` refetch query and the `network-only` query was therefore discarded.

My assumption would be that `refetchQueries` guarantees to sync the current store with the result returned from the server and that intermediate `cache-first` queries cannot interfere with this.

So, is this a bug or a feature? :)

**Comment by helfer** [comment]
Hi @ctavan, thanks for the very detailed bug report! I think this is definitely not a desired feature, so if you would be able to provide us with a reproduction using react-apollo-error-template, we should be able to fix this pretty quickly (or you could help us fix it by making a PR with a failing test!).

**Comment by fc** [comment]
@helfer it looks like he already provided a reproduction react-apollo-error-template (refer to the link in his post).

**Comment by ctavan** [comment]
Yes indeed @fc @helfer: The reproduction is here: https://github.com/ctavan/react-apollo-error-template/tree/reproduce-refetch-query-race

**Comment by aroth** [comment]
Also noticing this.

**Comment by jbaxleyiii** [comment]
@ctavan thank you for the great report! I'll take a look!

**Comment by ctavan** [comment]
The issue still persists and I believe this issue should not be closed.

**Comment by WiktorKa** [comment]
Is there any update on this issue?

**Comment by tsvetann** [comment]
...and in 2018 the issue is still alive :)

**Comment by SebastianMuniz** [comment]
I'm having the same issue! Please fix or provide some light about it.

**Comment by oduncan** [comment]
Running Into the same issue, It's as if Apollo was only intended for SPAs? What is the current work around?

**Comment by SebastianMuniz** [comment]
The workaround for this is to have a unique collection of records in a store and when you send a mutation you request all inserted fields and merge that into your store collection

**Comment by oduncan** [comment]
I am still learning, can you point me to a resource?

**Comment by SebastianMuniz** [comment]
I'm sorry I'cant. It's the solution i implemented myself for a particular case. Im using an app state container, in this case Mobx, I have a list of object record in the store, when i start my app I make a query to the backend asking for the list of records.
Then every time I make a mutation to add or subtract an object form the list, inside the mutation I select all the field of the object I'm adding. So when the object its inserted i get back the response with the object itself. So then i merge it to the coleection of record i got in the store.
I dont know if its more clear for you, hope so.

**Comment by oduncan** [comment]
Thank you.

**Comment by nickmarlou** [comment]
The issue is still here and with update mutation it's really wierd

**Comment by mortenab** [comment]
Also seeing this issue - any plans to fix it?

**Comment by alexgorbatchev** [comment]
I think the label applied incorrectly to the issue :)

**Comment by davidalekna** [comment]
I'm also having this issue but on Safari only

**Comment by vincentdesmares** [comment]
I can still reproduce it. I had to replace most of my query names by an object to solve the rendering issue:

```
{ 
  refetchQueries: [{
    query: myGraphQlQuery,
    variables: {
        id: 2
    }
  }]
}
```

As said previously, when using a string, the queries are fetched (they appear in the network tab) but the props are sometimes not updated.

I'm not sure the refetchQuery as a String are supported anymore as it doesn't appear in the [official doc](https://github.com/apollographql/apollo-client/blob/master/docs/source/advanced/caching.md).

Yet, there they have some tests and a few doc-strings reference them.

It would be nice if the maintainers could clearly state if this feature is supported or not. If yes, this ticket must be re-open, else, the documentation should be cleaned up and a deprecation warning should be added to help people migrate to the supported way.

**Comment by smirea** [comment]
any update on this? 
it's pretty painful right now to update the store and the `refetchQueries` with string options was a pretty clean solution that is not working.

**Comment by jpikora** [comment]
I think the race condition in question is the result of the fact that the mutation and refetchQueries promises are not chained.

Following the reproduction steps from @ctavan, the user is redirected to the List of People right after the create mutation gets resolved, not waiting for the People query to be refetched, which leaves the cache out of sync as the fresh data from refetch are discarded due to lower request ID.

In this scenario, the solution could be to refetch queries manually in resolve callback of the mutation promise e.g.

```
import { apolloClient } from '@/providers/apollo'

function refetchQueries (queries) {
  return Promise.all(queries.map(q => apolloClient.query(
    Object.assign({}, q, {
      fetchPolicy: 'network-only'
    })
  )))
}

apolloClient.mutate({
  ...
})
  .then(() => {
    refetchQueries([{
      query: PEOPLE_QUERY,
      variables: {
        ...
      }
    }])
  })
  .then(() => {
    // redirect
  })
```

#1618

**Comment by Maarondesigns** [comment]
I am still having the same issue however I have solved it temporarily with a recursive function that just keeps executing until the refetchQueries is completed.

```
this.props.myMutation({
    mutate: stuff,
    refetchQueries: [{query: getStuffBackFromDatabase}]
})
.then( data =>{
    let recursiveFunction = () => {
        let el = document.getElementById(data.whatever);
        if (el === null){
            console.log("not yet...");
            setTimeout(() => {
                recursiveFunction();
            }, 50);
        } else {
            doStuff
        }
    };
recursiveFunction();
});
```

**Comment by Emiliano-Bucci** [comment]
Any updates on this? Having the same weird issue: after a mutation, when refetchQueries is called with some variables, the cache-first data is the one who returns
