### ISSUE TITLE
Store error: the application attempted to write an object with no provided  id but the store already contains an id of...

### ISSUE THREAD

**Issue by hinok** [apollographql/apollo-client#2510]
Hey,
Today in one of my applications I found this issue. I'm not sure if this is a bug or desired behaviour because I couldn't find any information about in documentation.

The fix is quite easy, just add `id` to the `query` without id.

So, should every query has defined `id` for a resource?
It seems to work without `id` but when there will be the next query with defined `id`, this error appears.

**Intended outcome:**
Error shouldn't appear and application should render data.

**Actual outcome:**
Error appears

```
Network error: Error writing result to store for query 

query PokemonQuery($id: ID) { 
  Pokemon(id: $id) { 
    name 
    url 
    createdAt 
  } 
}

Store error: the application attempted to write an object with no provided 
id but the store already contains an id of Pokemon:ciwnmyvxn94uo0161477dicbm 
for this object.
```

**How to reproduce the issue:**
https://codesandbox.io/s/mom8ozyy9

Check `checkbox` in provided demo.

**Version**
- apollo-client@<1.6.0>

**Comment by jbaxleyiii** [comment]
Hey @hinok 👋 

This error only *should* occur when you have made a query with an `id` field for a portion, then made another that returns what would be the same object, but is missing the `id` field.

We are planning on making this just a warning (instead of throwing) but it does help a lot to keep the `id` field included in queries that share fields

**Comment by philcockfield** [comment]
Are you guys planning on converting this to a `warning` rather than error as @jbaxleyiii mentioned.  We're getting this too - fine to bring back `id`'s but a warning would be preferable.

**Comment by SanCoder-Q** [comment]
This `id` issue caused some of our production page failures too. I expect Apollo could do more than throw an error and break the whole page. An explicit configuration that indicates using a field like `id` as the key to share the resources would be good.

**Comment by johncade** [comment]
👍 this is a blocking error for me. Please fix

**Comment by matrunchyk** [comment]
We can't use it without in our projects with having this error.

**Comment by littletower** [comment]
any update on this issue @jbaxleyiii ?

**Comment by pencilcheck** [comment]
It seems like missing __typename on any level along side id field will also trigger this error

**Comment by deividmarques** [comment]
I have the same problem here, no solution so far?

**Comment by Mjafko** [comment]
Have a same problem :) Would like to see some solution...

**Comment by dennerevaldt** [comment]
Have a same problem.. :/

**Comment by razvangherghina** [comment]
+1

**Comment by eugenegodun** [comment]
+1

**Comment by georgetroughton** [comment]
+1

**Comment by mike-marcacci** [comment]
For what it’s worth, I don’t mind the current behavior, as long as it can be caught compile-time using a tool like `apollo-codegen`. The real issue here is that the scenarios that induce this error can be complex and missed by unit tests and quick human checks, but exist in real world usage.

**Comment by cmcaboy** [comment]
+1

**Comment by rcreasi** [comment]
+1

**Comment by billhanyu** [comment]
+1

**Comment by ramusus** [comment]
+1

**Comment by wuzhuzhu** [comment]
+1

**Comment by nicoosokhan** [comment]
You may forgot to select `id` in your query.

`query ($pagination: PaginationInput, $postID: ID!) {
                post(id: $postID) {
                    id
                    comments(pagination: $pagination) {
                        edges {
                            node {
                                content
                            }
                            cursor
                        }
                        pageInfo {
                            endCursor
                        }
                    }
                }
            }`

**Comment by bennypowers** [comment]
PSA: This can also happen if you try to *write* an object without an ID, as happened to me when I created an unauthenticated user by mutating with `{accessToken}` instead of `{accessToken, id, ...rest}`

**Comment by quadsurf** [comment]
@jbaxleyiii in your first response to hinok, you wrote: 
```it does help a lot to keep the id field **included** in queries```

The problem I'm running into is that I'm getting this exact error on a CREATE mutation... you're not supposed to **"include"** an ID for CREATE mutations because it's the CREATE mutation's job to return an ID in the response. But if an error keeps getting thrown, then a success response furnishing the ID that the store needs, is not possible. It's currently an app "show-stopper."

Please help!

**Comment by wfsovereign** [comment]
Find this [stack overflow](https://stackoverflow.com/questions/41944291/apollo-client-is-giving-me-an-error-of-store-already-contains-an-id-what-doe) can resolve my problem.

**Comment by developdeez** [comment]
Is this fixed? I asked a similar here?=:
https://stackoverflow.com/questions/53788200/fix-error-writing-to-store-for-query-queryname

**Comment by japrogramer** [comment]
same problem
```
  query PreviewResourceSearch($cat: [String!], $zips: [String], $page:Int) {
    searchResourcesPaged(categories: $cat, zipCodes: $zips, page: $page, perpage: 3) {
      resources {
        id
        internalId
        name
        phone
        streetAddress
        city
        state
      }
      numResults
      numPages
      keywords
    }
  }
```
```
function loadMore(data, path, page) {
  console.log(page)
  return data.fetchMore({
    variables: {
      page: page,
    },
    updateQuery(previousResult, { fetchMoreResult }) {
      const more = fetchMoreResult[path].resources;

      return {
        [path]: {
          resources: [ ...previousResult[path].resources, ...more],
          numPages: previousResult.numPages,
          numResults: previousResult.numResults,
          keywords: previousResult.keywords,
          __typename: previousResult.__typename
        },
      };
    },
  });
}

```

**Comment by vjsingh** [comment]
Not sure if it does any good to comment on closed issues, but at the least I think a more helpful warning would be great here

**Comment by alacret** [comment]
having this error

**Comment by njwest** [comment]
This is breaking routing for me when going from an overview view to an edit view, seems unable to re-fetch the data an update view

Scenario (Vue):

On a page showing information of object id=1
```
<router-link :to="{ name: 'Edit', params: { id: object.id }}">
...
```

On page showing update form of object id=1:
```
Error sending the query 'getObjectById' Invariant Violation: Store error: the application attempted to write an object with no provided id but the store already contains an id of Object:1 for this object. The selectionSet that was trying to be written is: // a bunch of empty directive / field: type: stuff omitted
```

This feels like a bug/caching issue...

**Comment by capaj** [comment]
Yeah me too, not sure why these issues keep getting closed. BTW this is a bug. If you require `id` field to be present in the query and you cannot cache it if it's not there then sensible thing to do would be to show a warning. Not an error.

**Comment by Abhijeetjaiswalit** [comment]
Same error

**Comment by alacret** [comment]
@capaj @Abhijeetjaiswalit just put the ID in all the Types, and that will solve the issue

**Comment by capaj** [comment]
@alacret what if I don't have ID on some of my object types?

I am sorry to say this, because I totally respect the work apollo team has done on apollo-client, but this issue is a shitshow. Excuse the profanity, but it seems that apollo team doesn't think this is an actual bug. yet even the most experienced people like https://twitter.com/thekitze/status/1113871705498370049 keep running into problems here.
They should either acknowledge this as a bug or they should amend documentation with a big red warning that you absolutely need to include `id` or `_id` field in all of the object types you query.

For all the people like me who still get this error daily on production apps where they can't magically add `id` field everywhere I've wrote this terrible hack that you can add to your apps that will at least keep your react app from breaking:
```js
window.onunhandledrejection = async (error) => {
  if (error.reason && error.reason.message && error.reason.message.match(/Error writing result to store for query/)) {

      /**
       * THIS is nasty and hacky, but it's the best mitigation for the apollo-client problem that we've got.
       * If we can't stop apollo-client to choke on these errors so often, we should just migrate every graphQL query/mutation to urql
       */
      apolloClient.cache.reset(), 

      const rootEl = document.getElementById('appRoot') // obviously modify according to your DOM

      console.log('apollo caches reset, remounting the app')
      ReactDOM.unmountComponentAtNode(rootEl)
      renderApp()
    }
  
}
```

**Comment by alacret** [comment]
@capaj That's a super hack bro.

I think that just apollo-client is not so battle-tested as other libraries. I'm assuming that the decision was based on the fact that using `id` or `_id` is pretty much a standard nowadays, and this was more relevant for the implementation of the cache than anything else.

But it makes sense that by now this should be just a warning and not an error, or maybe allow to skip any caching check, or to allow setting a different field name as the key for the cache.

**Comment by japrogramer** [comment]
like @alacret  suggests to @capaj , this might be the right direction .. still needs some tweaking maybe.
```
query {
  object @connection(key="someobject") {
    someobject {
      someField
    }
  }
}
```

**Comment by AdamZaczek** [comment]
This error is odd. It made one of our queries fail despite the fact that the query itself was just fine. There are valid cases for making similar nested queries where one has id and the other doesn't.
It's good that we are warned that Apollo is unable to update the store but it shouldn't break the app.

**Comment by mac-s-g** [comment]
will there be a warning published?
it's not practical for all objects to have an id attribute

**Comment by tabirkeland** [comment]
This is a major issue to utilize this library in production and has been open for almost 2 years?  What's going on with this?

**Comment by edpark11** [comment]
Is there a clear fix for this that (maybe) can simply show a warning if you try to run a graphl query without `id` defined? A bunch of people on my team have independently stumbled across this issue and it always takes about a day to figure out and resolve. If apollo-client could at least throw a warning when there is no id set on the query, at least we could create an automated ticket warning the developer that their query may (will) cause a bug. I/we would be very happy to support any efforts in this direction.

**Comment by capaj** [comment]
For all the people still experiencing this issue-I've finally found out what is causing this issue. What helped me was switching from `apollo-cache-inmemory` to `apollo-cache-hermes`.
I experimented with Hermes hoping to mitigate this ussue, but unfortunatelly it fails to update the cache the same as `apollo-cache-inmemory`. What is curious though is that hermes shows a very nice user friendly message, unlike  `apollo-cache-inmemory`. This lead me to a revelation that cache really hits this problem when it's trying to store an object type that is already in the cache with and ID, but the new object type is lacking it. So  `apollo-cache-inmemory` should work fine if you are meticolously consistent when querying your fields. If you omit `id` field everywhere for a certain object type it will happily work. If you use `id` field everywhere it will work correctly. Once you mix queries with and without id that's when cache blows up with this horrible error message.

This is not a bug-it's working as intended, it's just not documented anywhere-see this [spec](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/__tests__/__snapshots__/writeToStore.ts.snap).

**Comment by bichocj** [comment]
Be careful include `__typename` or avoid it if you're testing with MockProvider. But in some cases you have to include `__typename` allowing it in the MockProvider

**Comment by qeehong** [comment]
@wfsovereign , your answer enlighten a better picture, that is, just put id on every query or subquery that has an id field. Thanks 👍🏼

**Comment by emahuni** [comment]
The [Stackoverflow](https://stackoverflow.com/questions/41944291/apollo-client-is-giving-me-an-error-of-store-already-contains-an-id-what-doe) answer pointed to in this issue is actually the sensible one and actually solves this issue, which is not a bug by the way. I think this needs to be documented somewhere. In a nutshell:
**make sure to add id to all subselections of your queries** 
this makes sure the cache identifies queries and selections properly... notice this has nothing to do with following a certain pattern, it's just that simple; put ids for sub-selections and to add to that especially for ones that recurse!

**Comment by kidroca** [comment]
I have a similar issue when an alias is used for the `ID` field:

#### Example:

```graphql
query GetService ($id: ID!) {
    service(id: $id) {
        image
        # list of account types
        providers {
            id: provider_id
            firstName: first_name
            lastName: last_name
        }
    }

    self: account {
        # if I don't use an alias here it worked even when MyProviderAccount didn't include the `provider_id`
        id: provider_id
    }
}

query MyProviderAccount {
    # acount type
    account {
        provider_id # using the same alias here would fix the problem
        first_name
        last_name
    }
}
```

When I try to run the `MyProviderAccount` query after `GetService` I would get the error: 
> Store error: the application attempted to write an object with no provided id but the store already contains an id of ProviderType:501 for this object

I wasn't expecting that when I use an alias for a field, I have to use the same alias everywhere so that cache would work

**Comment by japrogramer** [comment]
@kidroca why not use a fragment with an alias .. that way now you only need to use the fragment everywhere.

**Comment by kidroca** [comment]
I am using a fragment where it makes sense. For example the `MyProviderAccount -> account`. But there are cases where I just want a few fields like in `self` -> I use the id to highlight the current user account in the `providers` list

---

I've read more about cache and looks like this is the correct behavior, because the cache doesn't exactly know which key is the `id` . It has a default logic to assume that if there is `object.id` then `id` is the ID 

1. The cache would map and normalize based on the received data
2. It can't tell which key is the ID, just by the data itself (it doesn't know the schema - doesn't have to)
3. It is smart enough to distinct whether and where you've used an alias though 
 
For this reasons I've decided that you should either always alias all ids in a generic way (`id: provider_id`, `id: service_id`) or never alias ids, which seems the easier option

When the ID key is different across your Types (provider_id, service_id), it's best to provide a `dataIdFromObject(object)` function which can map the id `=> getIdFor(object.__typename)` like the example provided in the docs.  And you can still fallback to the default `dataFromObject` function in case an alias like `id: provider_id` was used 

Also have in mind that if you're dealing with numeric ids - they probably aren't unique across types so the returned data for `dataIdFromObject` should be something like `${object.__typename}[${id}]` (e.g. `"Service[10]"`) and not just the `id`

**Comment by rmolinamir** [comment]
I wanted to chime in and report that this issue happens in the official example of the Hacker News clone: https://www.howtographql.com/basics/0-introduction/

The solution was to indeed modify the queries and add `id` fields to everything that was related to subscriptions.

It does make sense that it works as intended because it's essentially replacing data in the cache by their identifier keys, but the error message is lacking IMO.

**Comment by Vadorequest** [comment]
I ran into this today, I added a new subquery somewhere and it broke my whole app because it's a Next.js app which uses both SSR and CSR and depending on the cached data it would randomly crash.

For instance, refreshing a page with cmd+shift+r to erase cache would work fine (SSR) but then when navigating to another page (CSR) it would randomly crash THE WHOLE THING, depending on which page is loaded.

This definitely SHOULD NOT throw an exception, but rather a warning (as proposed in 2017).
And it should be made obvious in the docs that all query must have an "id" field for Apollo to work properly.

Also, it's very hard to debug. Especially because the error message isn't always `Store error: the application attempted to write an object with no provided id but the store already contains an id of` but most of the time only `Network error: Error writing result to store for query` with the whole query behind... Quite complicated to understand what's the issue at hand with such cryptic error messages.

I eventually added `id` everywhere, in all fragments and queries to avoid this, and it works fine now.

**Comment by balazsorban44** [comment]
Totally agree with @Vadorequest! Came here to say something similar

**Comment by cecchi** [comment]
This eventually became enough of a pain in the neck that we wrote a validation rule to ensure the "id" field was present in every possible GraphQL selection set. This rule is intended to be used with the [GraphQL validation APIs](https://graphql.org/graphql-js/validation/). 


<img width="810" alt="Screen Shot 2020-04-24 at 8 26 10 AM" src="https://user-images.githubusercontent.com/1663781/80229454-4f342f80-8605-11ea-899a-ba88a5425c05.png">


Our implementation is wrapped up in some other tooling but these are the relevant bits:

```ts
function IdOnObjectSelectionSetRule(context: ValidationContext): ASTVisitor {
  /**
    * Given a set of SelectionNodes from a SelectionSet, ensure "id" is included.
    */
  function selectionSetIncludesId(selectionNodes: readonly SelectionNode[]) {
    return selectionNodes.some(selectionNode => {
      switch (selectionNode.kind) {
        case 'Field':
          return selectionNode.name.value === 'id'

        // Fragments have their own selection sets. If they do not include an "id",
        //   we will catch it when we visit those selection sets.
        case 'FragmentSpread':
        case 'InlineFragment':
          return true
      }
    })
  }

  /**
    * Walk the AST and inspect every SelectionSetNode. Every SelectionSet must include an "id"
    *   field, if one exists. It can include it directly, or as part of a fragment.
    *
    * See: https://graphql.org/graphql-js/language/#visit
    */
  return {
    SelectionSet(node: SelectionSetNode) {
      let type = context.getType()

      // Unwrap NonNull types
      if (isNonNullType(type)) {
        type = type.ofType
      }

      // Ensure this is an object type (meaning it has fields)
      if (!isObjectType(type)) {
        return undefined
      }

      const possibleFieldsIncludesId = 'id' in type.getFields()

      if (possibleFieldsIncludesId && !selectionSetIncludesId(node.selections)) {
        context.reportError(
          new GraphQLError(
            `Missing \"id\" field in \"${type.name}\"`,
            node,
            undefined,
            undefined,
            // N.B. In our implementation we pass in the source location as well for more
            //  useful errors.
            location ? [location] : undefined
          )
        )
      }

      return undefined
    }
  }
}
```

Usage is something like this:

```ts
import { loadSchema, loadDocuments } from '@graphql-toolkit/core'

function validate(schemaAst: GraphQLSchema, sources: Source[]) {
  let errors: GraphQLError[] = []

  sources.forEach(source => {
    if (source.document) {
      errors = errors.concat(
        // If you want pretty errors, also make "source.location" available to the IdOnObjectSelectionSetRule
        validateGraphQL(schemaAst, source.document, [IdOnObjectSelectionSetRule])
      )
    }
  })

  return errors
}

// Load the schema and documents
const [schemaAst, documents] = await Promise.all([
  loadSchema(/*... your schema ...*/, {
    loaders: [new UrlLoader()]
  }),
  loadDocuments(/*... your documents ...*/, {
    loaders: [new GraphQLFileLoader()],
    skipGraphQLImport: true
  })
])

const errors = validate(schemaAst, documents)
```

**Comment by capaj** [comment]
@cecchi wow, this is amazing work! Someone should take that code and turn it into a code into a graphql-codegen plugin

**Comment by cecchi** [comment]
A plugin sounds like a good idea. We use `graphql-codegen` too, but we run them in series: validate followed by codegen. Since `graphql-codegen` uses `@graphql-toolkit` under the hood we're able to load the schema and documents once for both steps, using graphql-codegen's programmatic API.

If there's enough interest I can publish the validate fn as a standalone package.

**Comment by cheapsteak** [comment]
Looks like this is addressed in Apollo Client 3, specifically this PR from Ben to remove that error 
 https://github.com/apollographql/apollo-client/pull/5904
  
Here's the repro using `"@apollo/client": "3.0.0-beta.44"`, no longer erroring
https://codesandbox.io/s/github/cheapsteak/test-ac-cache-store-bug/tree/master/?file=/src/index.js

**Comment by stephenh** [comment]
@cecchi thanks for that visitor/linter! I dropped it into a graphql-code-generator plugin: https://github.com/homebound-team/graphql-id-linter cc @capaj

**Comment by bennypowers** [comment]
> @cecchi thanks for that visitor/linter! I dropped it into a graphql-code-generator plugin: https://github.com/homebound-team/graphql-id-linter cc @capaj

Looks like this wasn't published yet?

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@homebound%2fgraphql-id-linter - Not found
> npm ERR! 404 
> npm ERR! 404  '@homebound/graphql-id-linter@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by birhanuh** [comment]
@jbaxleyiii Thank you! You saved my day!

**Comment by stephenh** [comment]
@bennypowers shoot, I missed your comment, but I'd forgotten to make the `@homebound/graphql-id-linker~ npm module public; it should work now.

**Comment by jmtimko5** [comment]
This feels like a very important gotcha in using Apollo GQL that should be documented explicitly and obviously, and be added to standard Apollo linters. Can we add this to the docs?

**Comment by trackwell-mike** [comment]
Just confirming that we are using `"@apollo/client": "^3.1.3"` and are still seeing this "error" (logged as a WARN).

```
[Error: Error writing result to store for query: { ... } 
Store error: the application attempted to write an object with no provided id but the store already contains an id of User: ### for this object. The selectionSet that was trying to be written is: { ... }
```

**Comment by anarchist912** [comment]
Updated to `@apollo/client v3.4.5`, still had the issue. Would break my entire React component. Resolved it by making sure that  nested data in the schema has the ID field (whatever the field is named) queried as well, e.g.

```graphql
query {
  listOrder {
    _id
    customer {
       _id  <= YES, THIS IS NEEDED.
       name
    }
  }
}
```

**Comment by lsanwick** [comment]
I think the biggest that bothers me with this error is that it doesn't seem to fire the `onError` error link when it occurs, unlike traditional GraphQL errors.

**Comment by jamiemetca** [comment]
> Find this [stack overflow](https://stackoverflow.com/questions/41944291/apollo-client-is-giving-me-an-error-of-store-already-contains-an-id-what-doe) can resolve my problem.

Thanks @wfsovereign This solved my issue. Nested data also requires id.
From this;
```
  query CheckExists($input: Input) {
    checkExists(input: $input) {
      id
      name
      address {
        postcode
      }
      bank {
        accountNumber
      }
    }
  }
```
To this;
```
  query CheckExists($input: Input) {
    checkExists(input: $input) {
      id
      name
      address {
        id
        postcode
      }
      bank {
        id
        accountNumber
      }
    }
  }
```
