### ISSUE TITLE
[Crash] Object.setPrototypeOf(_this, ApolloError.prototype) on 2.2.8

### ISSUE THREAD

**Issue by alexmbp** [apollographql/apollo-client#3236]
I'm trying to do simple mutation and actually network request is happening and I'm receiving response. In case when response is error - code brakes immediately. Issue arrived only after update to 2.2.8. Downgrade to 2.2.7 helped and everything working as expected.

I'm using TypeScript compiler (latest one) and TSLib (latest one).

![image](https://user-images.githubusercontent.com/17987276/38140048-c8fa29b0-343a-11e8-9514-a57af1e226d5.png)

**Version**
- apollo-client@2.2.8

- [x] blocking

**Comment by seklyza** [comment]
+1 I'm also getting this error on Android when trying to do a simple mutation (create-react-native-app project)

**NOTE:** If there are no errors from the GraphQL server, it works, but the error handling is broken.

**Comment by alexmbp** [comment]
@seklyza Same here. Issue - android only. Are you using TS or something before RN babel?

**Comment by seklyza** [comment]
@alexmbp No. Just plain CRNA project. Not using TypeScript or something like that.

**Comment by lxcid** [comment]
+1, i think bundle.umd.js is using Object.setPrototypeOf which return null in Android.

```
Object.setPrototypeOf(_this, ApolloError.prototype);
```

See 

https://github.com/realm/realm-js/pull/1195/files

**Comment by doraeminemon** [comment]
Any way to sidestep this for now ?

**Comment by lxcid** [comment]
As noted by the original author of this post:

> Downgrade to 2.2.7 helped and everything working as expected.

**Comment by ropaillet** [comment]
Downgraded and not working :( any other solutions ? @lxcid , in what file do the changes you referred go ? Couldn´t find any realm package between mines.

**Comment by chrisehlee** [comment]
This is frustrating. Been trying to figure out what went wrong for the past few days. Downgraded mine as suggested but I still get the same old errors. As noted earlier by @doraeminemon , any sidestep would be appreciated.

**Comment by dozoisch** [comment]
@chrisehlee what exact version did you put in your package.json when downgrading? make sure to pin, because otherwise it'll resolve latest.

**Comment by chrisehlee** [comment]
@dozoisch For clarity here's the relevant part of my package.json

````
"apollo-boost": "^0.1.4",
"apollo-client": "2.2.7",
"apollo-link-context": "^1.0.7",
"react-apollo": "2.1.0-beta.3",
"react-native": "0.53.3",
"graphql": "^0.13.2",
"graphql-tag": "^2.8.0",
````

**Comment by FabricioCabeca** [comment]
@chrisehlee apollo-boost@0.1.4 depends on apollo-client@2.2.8, so you probably have both installed and is actually using 2.2.8, try downgrading apollo-boost to 0.1.3 instead.

**Comment by chrisehlee** [comment]
#### NB: I'm using wix/react-native-navigation and aws-amplify(-react-native).
@FabricioCabeca I've downgraded every related package but I'm still stuck.
Queries work almost fine except when response is error. Mutations, not so much.
Please anybody with a workaround is greatly appreciated. 

```
"apollo-boost": "0.1.3",
"apollo-client": "2.2.7",
"graphql": "0.13.1",
"graphql-tag": "^2.8.0",
"react-apollo": "2.1.0-beta.3"
```

**Comment by alexmbp** [comment]
Apollo boost still require ^2.2.7 which means version 2.2.8 is installed for you. I did have similar issue. I’ve fixed it by forcing webpack to use root node_modules, but it brakes a lot.
I think you have Apollo-client@2.2.7 in root and Apollo-client@2.2.8 in node_modules/Apollo-boost/node_modules.

**Comment by chrisehlee** [comment]
@alexmbp Woah, you're spot .. dug in and saw exactly what you said.
Installing 
``` "react-apollo": "2.1.0-rc.5" ```
did the trick of getting mutations to work. But every error response still crashes the app.
Thanks everyone.

**Comment by padil** [comment]
Any solutions to this?

**Comment by FabricioCabeca** [comment]
@chrisehlee actually I've just downgraded apollo-boost and apollo-client, react-apollo is at 2.1.2, here are my deps, working fine here:

```
  "dependencies": {
    "apollo-boost": "^0.1.3",
    "apollo-client": "^2.2.7",
    "axios": "^0.18.0",
    "expo": "^25.0.0",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.8.0",
    "query-string": "^6.0.0",
    "react": "16.2.0",
    "react-apollo": "^2.1.2",
    "react-native": "0.52.0",
    "react-native-masked-text": "^1.6.5",
    "react-native-scripts": "^1.11.1",
    "react-native-side-menu": "^1.1.3"
  }

```

**Comment by chrisehlee** [comment]
@FabricioCabeca I'm glad that worked for you and it's hard to go through all this hurdles .. however, any chance the official team is looking into this?

**Comment by atkit** [comment]
ok, workaround works, next step is to fix setPrototypeOf...

...ref that might work...
https://github.com/realm/realm-js/pull/1195/files

**Comment by chrisehlee** [comment]
@atkit Hello, any word yet?

**Comment by melloflavio** [comment]
@chrisehlee 
I noticed there's an open [PR#3306](https://github.com/apollographql/apollo-client/pull/3306).
I'm not sure how long it will take for it to be accepted.

In the meantime, I'm doing the same as @FabricioCabeca and bump down `apollo-client` to `2.2.7`. The initial tests went OK...

**Comment by chrisehlee** [comment]
@melloflavio
I've done the same too .. however let's hope the PR gets reviewed and officially merged.

Thanks.

**Comment by MichelDiz** [comment]
For me Downgrade apollo-boost doesn't work. By the way, who use apollo-boost don't need apollo-client. It's built in. I'm using React-native (Had this with expo too).

**Comment by seklyza** [comment]
@MichelDiz downgrading `apollo-boost` did not work either, I had to replace apollo-boost with the alternatives (client, link, cache, etc)

**Comment by MichelDiz** [comment]
That's odd and boring, I'll have to do the same.

**Comment by padupuy** [comment]
Here is my workaround 

1. Create a patch file `apollo.patch` with this content : 
```
--- node_modules/apollo-client/bundle.umd.js	2018-04-25 15:16:30.000000000 +0200
+++ bundle.umd.js	2018-04-25 15:16:49.000000000 +0200
@@ -128,7 +128,7 @@
             _this.message = errorMessage;
         }
         _this.extraInfo = extraInfo;
-        Object.setPrototypeOf(_this, ApolloError.prototype);
+        _this.__proto__ = ApolloError.prototype;
         return _this;
     }
     return ApolloError;

```

2. Add a `postinstall` hook to `package.json`
```
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "postinstall": "patch -p0 < patch/apollo.patch || true"
    },
```

3. Now when you or your CI will install the dependencies, the patch will be apply.

The patch has been created from the commande line from PR PR#3306 :
```
diff -u node_modules/apollo-client/bundle.umd.js bundle.umd.js> apollo.patch
```

**Comment by MichelDiz** [comment]
@padupuy  Thank you very much! u saved my sanity!
It's working perfectly on Android, work like a charm. I'll no longer lose hair!
You're a good person xD

**Comment by The-FZ** [comment]
Where to write the apollo.patch ?
How to do that can you please elaborate as I am completely new to graphQl and apollo thing.
Thank you and hope to see your answers real soon.

**Comment by crs2here** [comment]
when I try to add the patch I receive the following 
```
> patch -p0 < patch/apollo.patch || true

can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- node_modules/apollo-client/bundle.umd.js	
|+++ bundle.umd.js	
--------------------------
File to patch: 

```

**Comment by Monte9** [comment]
I ran into this as well and it's so frustrating that something so crucial as running apollo-client + react native android is not working when graphql returns an error response. 

Luckily, @FabricioCabeca's solution worked out. Thanks a lot 🎉 

Just to reiterate, here is what fixed it for me:
1. Change the following package.json versions:
```
"apollo-boost": "0.1.3",
"apollo-client": "2.2.7",
"react-apollo": "2.1.2",
```

2. Clean install your npm packages
```
rm -rf node_modules
npm install
```

3. Start react native packager with cache clean
```
react-native start --reset-cache
```

And hopefully, that should do it. Hope this helps.

**Comment by Tommos0** [comment]
+1, took me hours to locate this error.
My <Query /> would just never update and keep loading forever. So I wasn't even getting an exception anywhere (I guess it was caught somewhere in Apollo Client).

My workaround: a simple polyfill:
```javascript
Object.setPrototypeOf = Object.setPrototypeOf || function (obj, proto) {
  obj.__proto__ = proto
  return obj
}
```

**Comment by ujwal-setlur** [comment]
@Tommos0, thanks! Your polyfill worked!

**Comment by DiwakarShukla1** [comment]
Polyfill worked for me too. @Tommos0 thank you very much.

**Comment by hwillson** [comment]
PR https://github.com/apollographql/apollo-client/pull/3306 has been merged (and will be included in the next `apollo-client` release). Thanks for the additional troubleshooting details everyone, and thanks @seklyza for working on a fix!

**Comment by seklyza** [comment]
Thank you guys. It was a pleasure to work with you.

**Comment by rizwan92** [comment]
i am also getting the same error is there any solution 
`undefined is not a function (evaluating 'Object.setPrototypeOf(_this, ApolloError.prototype)' )  on 2.2.7` 
what should i do?

**Comment by sijad** [comment]
same here

**Comment by ujwal-setlur** [comment]
Folks, solutions have been proposed here. Please confirm you have tried the solution before you say you still see the problem.

**Comment by dafapramudya** [comment]
@ujwal-setlur how can i use polyfill? i'm sorry if I ask a lot, because I never use polyfill

**Comment by dafapramudya** [comment]
SOLVED thank you @Tommos0  @ujwal-setlur. Solved using polyfill

**Comment by Seunope** [comment]
I also experienced this same issue. I tried all the solutions above but none worked. I later discovered that apolloClient was pointing to the wrong url. When i fixed this the error disappeared

`import React from 'react';
import {AsyncStorage} from 'react-native';
import ApolloClient from 'apollo-boost';
import gql from "graphql-tag";

export const client = new ApolloClient({
  // uri: 'http://10.0.2.2:4800/graphql',
  uri: 'http://192.168.1.107:4800/graphql',
  
  request: async (operation) => {
    const token = await AsyncStorage.getItem('@keep_token');
    if(token){
      operation.setContext({
        headers: {
          authorization: token ? `Bearer ${token}` : null
        }
      }); 
    }
  },`
