### ISSUE TITLE
[apollo-boost] Ignores `fetchOptions.credentials`

### ISSUE THREAD

**Issue by alexgorbatchev** [apollographql/apollo-client#3265]
**Intended outcome:**

Have credential being included with GraphQL request across different domains. 

**Actual outcome:**

Credentials aren't included.

**How to reproduce the issue:**
```js
import ApolloClient from 'apollo-boost'; 

const client = new ApolloClient({
  fetchOptions: {
    credentials: 'include',
  },
  uri: GRAPHQL_URI,
});
```

**Version**
- "apollo-boost": "^0.1.3"

Credentials value is hardcoded over here
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L77

I submitted a PR at #3264

**Comment by alexgorbatchev** [comment]
You can manually configure the client using the sample below:

```js
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new HttpLink({
    credentials: 'include',
    uri: GRAPHQL_URI,
  }),
});
```

**Comment by MinJieLiu** [comment]
I have the same problem.

**Comment by haflinger** [comment]
Same here.

**Comment by haflinger** [comment]
```javascript
const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: 'http://localhost:4000/graphql',
  request: async operation => {
    operation.setContext({
      fetchOptions: {
        credentials: 'include'
      }
    });
  }
});```

Here is my solution.

**Comment by MinJieLiu** [comment]
Why does the author not give priority to this bug?

**Comment by StoraH** [comment]
@alexgorbatchev @haflinger thank you! Spent a lite too mutch time before I found this issue. Two days I'm not getting back 😅

**Comment by wesbos** [comment]
whew- thank you for this - just spent the last hour trying to find out why cookies were not being sent :)

**Comment by wesbos** [comment]
I think this is the fix: https://github.com/apollographql/apollo-client/pull/3387

**Comment by alexgorbatchev** [comment]
@wesbos i submitted a PR with this issue #3264

**Comment by hwillson** [comment]
Hi all - this has been fixed by https://github.com/apollographql/apollo-client/pull/3098, and has been merged in. It will be included in our next release (this upcoming Tuesday, June 12th). Thanks!

**Comment by wooolfgang** [comment]
This is still not working for me. Using apollo-boost my cookies are not stored/persisted, currently using apollo-link as instead. The code below does not save cookies

```
import ApolloBoostClient from "apollo-boost";
const client = new ApolloBoostClient({
  fetchOptions: {
    credentials: 'include',
  },
  uri: "http://localhost:4000/"
});
```
While these do.

```
import { ApolloClient } from 'apollo-client'
const client = new ApolloClient({
  link: createHttpLink({
    uri: "http://localhost:4000",
    credentials: "include"
  }),
  cache: new InMemoryCache()
})
```

Versions used:
```
"apollo-boost": "^0.1.16",
"apollo-cache-inmemory": "^1.3.5",
"apollo-client": "^2.4.2",
"apollo-link-http": "^1.5.5",
```

**Comment by leogoesger** [comment]
@hwillson I am using `"apollo-client": "^2.4.7",` with `"apollo-boost": "^0.1.22",`. This issue is still here. 

Using Appllo boost doesn't work, but apollo-client works as normal
`
export const client = new ApolloBoostClient({
  uri: process.env.SERVER_ADDRESS || 'http://localhost:8080/api/graphql',
  fetchOptions: {
    credentials: 'include',
  },
});

export const client = new ApolloClient({
  link: createHttpLink({
    credentials: 'include',
    uri: 'http://localhost:8080/api/graphql',
  }),
  cache: new InMemoryCache(),
});`
