### ISSUE TITLE
'graphql' is not exported by node_modules/graphql-anywhere/lib/async.js

### ISSUE THREAD

**Issue by arjunyel** [apollographql/apollo-client#3276]
**Intended outcome:**

Following the [Apollo boost tutorial](https://www.apollographql.com/docs/react/essentials/get-started.html) in a Stencil application, it should compile.

**Actual outcome:**

> [ ERROR ]  bundling: node_modules/apollo-link-state/lib/index.js, line: 13
           'graphql' is not exported by node_modules/graphql-anywhere/lib/async.js

**How to reproduce the issue:**

npm install then npm start this reproduction repo, Apollo code is in src/components/my-app/my-app.tsx: https://github.com/arjunyel/stencil-apollo-error

**Version**
- apollo-client@2.2.8

**Comment by arjunyel** [comment]
Looks like this is a Stencil error, sorry about that https://github.com/ionic-team/stencil/issues/652

**Comment by bennypowers** [comment]
For the record I have the same issue when trying to bundle with rollup, no stencil involved.

**Comment by bennypowers** [comment]
if I (manually) change the import statement in `node_modules/apollo-link-state/lib/index.js` to:
```js
import async from 'graphql-anywhere/lib/async';
const { graphql } = async;
```
then it works. 

potential solutions:
* refactor graphql-anywhere to es modules (preferred) 
* use namedExports feature of rollup-plugin-commonjs?

**Comment by arjunyel** [comment]
I've reopened the issue

**Comment by hwillson** [comment]
This was resolved in https://github.com/apollographql/apollo-link-state/pull/244. Thanks!

**Comment by touhonoob** [comment]
@hwillson As I've experienced the issue still exists with the latest version of apollo-client since the fix of apollo-link-state hasn't been published on npm.
