### ISSUE TITLE
FetchPolicy `cache-and-network` always uses networkStatus = 1 regardless of cache hit

### ISSUE THREAD

**Issue by nrdobie** [apollographql/apollo-client#3660]
**Intended outcome:**

This is the issue I originally found but it appears that the issue is with the `client` and not the `Query` component. apollographql/react-apollo#1217

When using the `cache-and-network` fetch policy I should be able to identify when I have data from the cache and when it is first retrieving the data.

```
<Query query={gql`{ now }`  fetchPolicy="cache-and-network" notifyOnNetworkStatusChange>
  {(data, error, networkStatus) => (
    if (networkStatus < 4) return 'Loading'
    if (error) return 'Error!'

    return <div>
      <time>data.now</time>
      {networkStatus === 4 && 'Refeshing'}
    </div>
  )}
</Query>
```

_The query `{ now }` returns the current date and time._

I would expect `networkStatus` to be `1` when it is making the first request, but `4` on each subsequent test as it is refetching the data.

**Actual outcome:**

Today the first request and subsequent requests come in using `networkStatus = 1` making it difficult to identify the difference between the two states.

**Versions**

  System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 8.9.3 - ~/.nvm/versions/node/v8.9.3/bin/node
    Yarn: 1.6.0 - ~/.nvm/versions/node/v8.9.3/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v8.9.3/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0
    Safari: 11.1

**Comment by rtymchyk** [comment]
For anyone dealing with this PITA bug, an alternative is to use `network-only` fetchPolicy. For whatever reason it functions exactly the same as `cache-then-network` in my case, but reports correct network statuses.

**Comment by frederikhors** [comment]
@rtymchyk are you sure? With `network-only` the cache is not considered, or it is bugged?

@all any news on this bug (FetchPolicy `cache-and-network` always uses networkStatus = 1 regardless of cache hit)?

**Comment by rtymchyk** [comment]
@frederikhors The network fetch happens with an explicit refetch only, which works well enough for me. Don't see much of an alternative 😢

**Comment by frederikhors** [comment]
@dallonf can you make a new smaller PR just for this problem in 2.0 land?

**Comment by dallonf** [comment]
I'm not an Apollo maintainer, just a guy who wrote a (declined) PR once

**Comment by frederikhors** [comment]
@dallonf yes, I know. But maybe in that period there was a mess with 2.0 coming. Can you just re-write a smaller PR just for fix this? When you done I personally commit my time to assure it passes.

**Comment by dallonf** [comment]
I could try, but I'm no more qualified than anybody else looking at this issue, and I don't have a lot of time to contribute to OSS at the moment, so if you really need this fixed ASAP, you're probably going to have to write the PR yourself.

It's also worth noting that my original PR(https://github.com/apollographql/apollo-client/pull/1607) isn't a "fix" - I diagnosed the problem as a gap in the design and added a whole new API to distinguish between two currently ambiguous states. This is something I really wouldn't be comfortable committing a lot of time developing until I have confirmation from the maintainers that this is a PR they would support; I don't want it to get ignored until the whole codebase changes out from under it again.

**Comment by jsslai** [comment]
Can someone confirm how this should work? I mean different network policies and how they affect response data and network status?

**Comment by hobochild** [comment]
I'm seeing a similar issue. Basically, I make a query with `cache-and-network` it returns it from the cache and sets the `networkStatus` to `7`. It then makes the remote request and so the `networkStatus` is set to `1`. 

I tried to solve the issue by manually running `markQueryResult()` for the said queries but they still didn't update. It seems to be some disconnect between the query manager and react-apollo. 

I have a feeling this is the offending [code](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L420) As you can see the promise isn't return like the other fetch-policies. I tried a few things but couldn't get the networkStatus to update. 

Any ideas?

**Comment by elitan** [comment]
> Can someone confirm how this should work? I mean different network policies and how they affect response data and network status?

Good question. I was expecting something like:

First load (no cache):

1.
data: empty
networkStatus: 1

2.
data: got data (fresh data)
networkStatus: 7

3.
Reload component

4.
data: data (cached)
networkStatus: 4

5
data: data (fresh)
networkStatus: 7


The important step here is step 4 where we get an indication that the `networkStatus` is not 1. That way we can differentiate that state from the first state when we got no data at all. If net `networkStatus` in step 5 should be `4` is more uncertain, but it seems to be the most fitting according to https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/networkStatus.ts#L4.

**Comment by wilcoschoneveld** [comment]
I have the same issue. Only way to distinguish a cache hit is to use something like:

```
if (!data || (loading && !data.documents)) {
    return <CardLoader />;
}
```

This is suboptimal because I cannot re-use this logic across different Query-components. Would prefer to have something like `networkStatus=4`.

@hwillson  any comments? Thanks!

**Comment by cem2ran** [comment]
Would be great to resolve this issue by either acknowledging that this is a bug and will be fixed, such that there's only a loading state when our cache is empty or introduce a non-breaking additive "cache-then-network" policy which does the above.

**Comment by shelmire** [comment]
Would be nice to see this resolved so we can have reusable logic.

**Comment by revskill10** [comment]
What's difference between `cache-first` and `cache-and-network` though ? These policies seems identical to me, so if it's better to remove the latter for not confusing users ?

**Comment by rstrand** [comment]
@revskill10 With `cache-first` if the data is found in the cache then no network request is made. `cache-and-network` will return data from the cache but will also make a network request (even on a cache hit) and return updated data if available.

**Comment by Emiliano-Bucci** [comment]
Is there a way (using cache-and-network) to do not update the cache if the data received after the network request is the same as the old one in the cache? Let's say i have a blog: the user enters in one article and it loads fast (since the data is in the cache); but if the autor of the artiche made some update, then apollo updates the relevant data, and react updates the relative component. Now it always update the cache.

**Comment by MrLoh** [comment]
It's a bit concerning that this issue has had no attention from the team at all in 8 months. 

A workaround to check wether data has been resolved from cache is to use `isEmpty(data)` from `lodash` or something similar.

**Comment by benjamn** [comment]
We just published the final version of `apollo-client@2.6.0` to npm, including the fix for this issue! See [`CHANGELOG.md`](https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md#apollo-client-260) if you're curious about the other changes in this release.

**Comment by antiold** [comment]
Still not working for me. I do not think `cache-and-network` is refetching (test file) the query therefore networkStatus is never 4.

**Comment by thompk2** [comment]
I'm running into the same issue as @antiold. with `apollo-client@2.6.0` I see `networkStatus` updating to in progress on initial load, but `networkStatus` still isn't updating on a refetch

**Comment by TheoMer** [comment]
I can confirm that this is still an issue for me with Apollo-client 2.6.3 and a fetchPolicy of cache-and-network.

**Comment by brianbolnick** [comment]
This is an issue for us as well. It looks like `refetch` is trying to pull from the cache with `cache-and-network` set as the fetch-policy. We were able to temporarily able to fix this by adding a dummy variable to the refetch

**Comment by kylesuss** [comment]
@benjamn I have created a simplified reproduction of this problem on Apollo client 2.6.4, which I think is still an issue. See:

https://codesandbox.io/s/apollo-cache-network-issue-miren

Notice that when you toggle the component which has the query back to visibility, it always goes from networkStatus 1 -> 7. Given the `cache-and-network` fetchPolicy is used, why aren't we seeing it at 4? My expectation is that when the query component is shown for the 2nd time, that it will have a network status of 4.

**Comment by seeruk** [comment]
This is a bit of an old issue, but it seems like it has the most relevant discussion.

I'm working on something at the moment where the view updates and I'm using cache-and-network to keep the interface feeling fast, while also being kept up-to-date.

I'm really struggling to figure out how to show loading states when I don't have cached data, but no loading state when I got data from the cache and Apollo is fetching the fresh data in the background. The problem is, when I don't have cached data, I still have the previous data returned from the hook, so I can't react to not having data, and loading is always true whenever it's loading either fresh data, or data in the background - so I can't use that either.

The closest I've come is reacting to when data changes, then comparing the new data with the old data to see if it's different, and if it's the same when loading is true then it must be the previous data. But it seems to bug out sometimes.

IMO what would be ideal is a different state when loading after data has been returned from the cache, so you could check loading === true and some network status that is something like "fetchingInBackground" (or maybe something more concise...)

**Comment by renato** [comment]
I've forked @kylesuss reproduction using `@apollo/client` 3.1.3: https://codesandbox.io/s/apollo-cache-network-issue-ck662, the behavior is the same.

**Comment by puglyfe** [comment]
I'm also running into this issue while trying to get setup with [apollo-cache-persist](https://github.com/apollographql/apollo-cache-persist). In the interest of a workaround that doesn't require refactoring the render logic of existing queries, I created a `usePersistedCacheQuery` hook that wraps `useQuery` and modifies the `loading` attribute to only return true if the query result doesn't already exist in the cache.

```
import { useQuery } from '@apollo/client';

const usePersistedCacheQuery = (query, options) => {
  const result = useQuery(query, {
    ...options,
    fetchPolicy: 'cache-and-network',
  });

  const isActuallyLoading =
    result.loading &&
    !result.client.readQuery({
      query,
      variables: options?.variables,
    });

  return { ...result, loading: isActuallyLoading };
};

export default usePersistedCacheQuery;
```
