### ISSUE TITLE
Truncated API documentation

### ISSUE THREAD

**Issue by PowerKiKi** [apollographql/apollo-client#4078]
**Intended outcome:**

The API documentation published on https://www.apollographql.com/docs/react/api/apollo-client.html should include as much information as possible.

**Actual outcome:**

The API documentation is truncated and only the first paragraph of the JSDoc comment appears. This "hide" a lot of very important information that would be useful to API users.

**How to reproduce the issue:**

Typically `setVariables()` has an important explanation on why it should not be used at all in the JSDoc:

https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/ObservableQuery.ts#L432-L459

But only the first paragraph appears in the documentation and parameter explanation is also totally absent: https://www.apollographql.com/docs/react/api/apollo-client.html#ObservableQuery.setVariables

**Versions**

any version, as it is doc related

**Comment by kanishk98** [comment]
Hello! 
I was just going through the issues here and noticed that this hasn't been addressed yet. Is there a particular reason for that? (since there are several other methods which have similar explanations, I figured that the docs might be shooting for brevity).

**Comment by PowerKiKi** [comment]
As it is labeled as "help wanted", I assume somebody should provide a PR. But I won't be able to do it myself.

**Comment by hwillson** [comment]
This issue was fixed - thanks!

**Comment by PowerKiKi** [comment]
I am afraid this is not solved yet. Checking out latest commit on main, 22510877782c13a1db4e0eb47e62201b20616c9c, and running 

```sh
cd docs/ && npm i && npm run types && npm start
```
will still serve a very incomplete documentation missing crucial information a shown in the screenshot below.

@hwillson could you please re-open the issue, as I am [not allowed to do that](https://stackoverflow.com/a/21333938/37706) ?


![image](https://user-images.githubusercontent.com/72603/116342941-6ad8a400-a81e-11eb-9053-145f48bb5033.png)

**Comment by PowerKiKi** [comment]
I believe the issue is in [that function](https://github.com/apollographql/gatsby-theme-apollo/blob/d8ec5dbe79c2961a5bd999255c92705b4d47272c/packages/gatsby-theme-apollo-docs/src/components/typescript-api-box.js#L36-L45) where both `shortText` and `text` should be concatenated.

**Comment by PowerKiKi** [comment]
I just created https://github.com/apollographql/gatsby-theme-apollo/pull/189 to fix the most critical part. The argument description is still missing though, but I can live with that, and it can come later.
