### ISSUE TITLE
Could not find module in path: 'graphql-anywhere/lib/async' relative to '/node_modules/apollo-link-rest/bundle.umd.js'

### ISSUE THREAD

**Issue by MrDestroii** [apollographql/apollo-client#4507]
> Could not find module in path: 'graphql-anywhere/lib/async' relative to '/node_modules/apollo-link-rest/bundle.umd.js' 

I have a problem with apollo-link-rest. This can even be seen from the example in the apollo-link-rest repository.

https://codesandbox.io/s/github/apollographql/apollo-link-rest/tree/master/examples/simple

**Comment by hwillson** [comment]
@MrDestroii this should be fixed by updating to `apollo-client@2.5.1` - thanks!

**Comment by marcobiedermann** [comment]
@hwillson 

Still not working for me. I had to install `graphql-anywhere`

```json
{
  "apollo-client": "^2.6.3",
  "apollo-link-rest": "^0.7.3",
  "graphql-anywhere": "^4.2.4",
}
```

**Comment by citypaul** [comment]
I can confirm I had to install `graphql-anywhere` just now to get apollo link rest working.
