### ISSUE TITLE
Reactive variables: Updating nested properties doesn't trigger a re-render

### ISSUE THREAD

**Issue by ryands17** [apollographql/apollo-client#6699]
**Intended outcome:**

Following [this](https://www.apollographql.com/blog/local-state-management-with-reactive-variables/) blog post for working with reactive variables, updating a nested value in the reactive variable doesn't re-render the React app.

```ts
import { InMemoryCache, makeVar } from '@apollo/client'
import { uuidv4 } from './utils'

export type Task = {
  id: string
  text: string
  completed: boolean
}

export type Tasks = Task[]

export const cache: InMemoryCache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        tasks: {
          read() {
            return tasks()
          },
        },
      },
    },
  },
})

const initialTasks: Tasks = [
  {
    id: uuidv4(),
    text: 'Task 1',
    completed: true,
  },
  {
    id: uuidv4(),
    text: 'Task 2',
    completed: false,
  },
]

const tasks = makeVar<Tasks>(initialTasks)

export const taskOperations = {
  addtask(text: string) {
    let initialTasks = tasks()
    let task: Task = {
      id: uuidv4(),
      text,
      completed: false,
    }
    tasks([...initialTasks, task])
  },
  toggleTask(id: string) {
    let initialTasks = tasks()
    let index = initialTasks.findIndex(task => task.id === id)
    if (index !== -1) {
      tasks(
        initialTasks.map((task, i) => {
          if (i === index) {
            task.completed = !task.completed
          }
          return task
        })
      )
    }
  },
}
``` 

Here, the `addTask` method triggers a re-render, but the `toggleTask` method doesn't.

**Actual outcome:**

The `toggleTask` method should trigger a re-render

**Versions**

System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
  npmPackages:
    @apollo/client: ^3.0.2 => 3.0.2

**Comment by ryands17** [comment]
So I tried updating the reactive var with [Immer](https://immerjs.github.io/immer/docs/introduction) and it works. So are changes not detected when we use the spread(...) operator and it that bad practice with Reactive vars?

**Comment by benjamn** [comment]
@ryands17 Can you show the code that issues/consumes the query (likely calling `useQuery` if you're using React)? Everything you've shown here looks good, so I'm at a bit of a loss. In case you were wondering, `tasks(initialTasks.map(...))` should always trigger an update, because the result of the mapping is always a new array object.

My only thought is that this code
```ts
task.completed = !task.completed
```
should perhaps be
```ts
task = { ...task, completed: !task.completed }
```
to ensure the `task` object itself is changing (in the `!==` sense).

**Comment by ryands17** [comment]
I have a repo setup [here](https://github.com/ryands17/react-apollo-linkstate) that uses Immer for now.

On this line in this method:
https://github.com/ryands17/react-apollo-linkstate/blob/e06089afb4d30530701db2f533d1499e60050a23/src/config/state.ts#L53-L63

If we convert the code in the method to this:

```ts
    let initialTasks = tasks()
    let index = initialTasks.findIndex(task => task.id === id)
    if (index !== -1) {
      let newTasks = [...initialTasks]
      newTasks[index].completed = !newTasks[index].completed
      tasks(newTasks)
    }
```

The new state isn't reflected and the component doesn't re-render.

**Comment by benjamn** [comment]
That code still seems to be modifying properties of the `task` objects in-place. Hence my suggestion about doing `task = { ...task, completed: !task.completed }` instead. You shouldn't _need_ a library to do simple immutable/non-destructive updates to JS objects.

**Comment by ryands17** [comment]
Yes I would need to copy the particular task as well.
Just a side question. do reactive variables work differently and shallow copying the main variable isn't enough like we do in React's for e.g.?

**Comment by limekiln** [comment]
Could it be there is an issue with reading reactive variables anyway? Using `useQuery` to consume the variable, it works perfectly fine. If I read the value directly by calling the reactive variable function without arguments, no update is triggered. My update function looks as follows:

```javascript
const updateVar = ({ dataVar, data }) => {
    const cachedData = dataVar();
    if (typeof cachedData === "object" && !Array.isArray(cachedData))
      dataVar(
        Object.keys(cachedData).reduce((acc, curr) => {
          if (!data) acc[curr] = null;
          else acc[curr] = data?.[curr] ? data[curr] : cachedData[curr];
          return acc;
        }, {})
      );
    else dataVar(data);
  };
```
My variable has the following structure:
```javascript
export const myVar= makeVar({
  fieldA: { propA: null, propB: "", propC: null },
  fieldB: { propA: null, propB: "", propC: null },
  fieldC: { propA: null, propB: "", propC: null },
  fieldD: { propA: null, propB: "", propC: null },
  fieldE: null
});
```
Updates of field A to D, while creating a new object, do not trigger a UI update this way. Am I missing something here?

**Comment by limekiln** [comment]
I just tried using the current 3.2.0 beta and its `useReactiveVar` hook, that seems to work properly.

**Comment by limekiln** [comment]
An update on this issue: The missing rerender seems to occur as well while using `useReactiveVar` if it is used within another custom hook. Calling `reactiveVar()` returns the correct value while `useReactiveVar(reactiveVar)` is always delayed by 1 render cycle.

**Comment by cyril36** [comment]
@limekiln can you show your code, i have the same issue, i have tried to use useReactiveVar but it seems that i dont use it properly

**Comment by limekiln** [comment]
As it seems, update 3.3.7 did break the `useReactiveVar` hook, so it seems there is no way now using reactive variables to reliably trigger a rerender.

**Comment by brainkim** [comment]
I am reasonably certain this is fixed by #8022. Feel free to ping and yell at me if this is not the case 🤗 Should be in a release soon.

**Comment by brainkim** [comment]
Shipped in 3.3.16

**Comment by hjrobinson** [comment]
I'm using @apollo/client": "^3.5.10" and was still having issues with the component not re-rendering when I update a reactive variable and use the useReactiveVariable hook. For example, importing the reactive variable into the component I wanted to update and then using the useReactiveVariable hook inside of it did not work for me. But I found that if I make the rendering of this component dependent on the presence of the reactive variable in its parent then it would update on every change to the reactive variable.  See example below. 

``````
import { useReactiveVar } from "@apollo/client";
import { myReactiveVar } from './cache';
import { ComponentToUpdate} from './ComponentToUpdate';

const MyComponent = () => {
      const reactiveVariableInUse = useReactiveVar(myReactiveVar );
      return (
          <React.Fragment>
               {reactiveVariableInUse && <ComponentToUpdate/>}
         </React.Fragment>
     )
}

``````

To be more specific my reactive variable consisted of an array of cart items and changes to the variable would not update the result of the reduce method. But using the example above I was able to get around this. Here is a snippet explaining what I was trying to update:

``````
  <React.Fragment>
        <h2>
            Subtotal ({cartItems.reduce((a, c) => a + c.quantity, 0)} items) : $
            {cartItems.reduce((a, c) => a + c.product.price * c.quantity, 0)}
        </h2>
  </React.Fragment>
```````

If anyone is having similar issues I hope this helps.
