### ISSUE TITLE
Breaking change from 3.0.2 to 3.1.0 [ MockedProvider ]

### ISSUE THREAD

**Issue by tyagow** [apollographql/apollo-client#6803]
**Intended outcome:**
Be able to mock a query using MockProvider
```
import { MockedProvider } from '@apollo/client/testing';
import { GET_TEACHERS_AND_ADMINS_OF_MY_DISTRICT_QUERY } from '../queries';

const mocks = [
  {
    request: {
      query: GET_TEACHERS_AND_ADMINS_OF_MY_DISTRICT_QUERY,
    },
    result: {
      loading: false,
      error: null,
      data: {
        teachersAndAdminsOfMyDistrict: [
          {
          [...]
...
      <MockedProvider mocks={mocks} addTypename={false}>
        <ComponentThatUsesTheQuery  />
      </MockedProvider>
```
**Actual outcome:**

After updating to 3.1.0 tests broke with:
```
    No more mocked responses for the query: {
      teachersAndAdminsOfMyDistrict {
      [...]
```

**How to reproduce the issue:**
Described in the first section but if more info is needed I can add here.

**Versions**
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 79.0
  npmPackages:
    @apollo/client: ^3.1.0 => 3.1.0 
    apollo-upload-client: ^14.1.0 => 14.1.0 
```

**Comment by mikevercoelen** [comment]
+1 

We're also experiencing this issue

**Comment by mikevercoelen** [comment]
@tyagow as a work around, you can mock `useQuery` like so:

```js
import * as Apollo from '@apollo/client';

jest.spyOn(Apollo, 'useQuery').mockImplementation(() => {
    return {
        loading: false,
        error: undefined,
        data: { MOCK_DATA },
        refetch: jest.fn()
    }
});
```

**Comment by tyagow** [comment]
> @tyagow as a work around, you can mock `useQuery` like so:
> 
> ```js
> import * as Apollo from '@apollo/client';
> 
> jest.spyOn(Apollo, 'useQuery').mockImplementation(() => {
>     return {
>         loading: false,
>         error: undefined,
>         data: { MOCK_DATA },
>         refetch: jest.fn()
>     }
> });
> ```

Thank you, great idea!
In the end, I used the new mock wrapper we created that uses the schema.graphql to auto-generate responses, here is a draft:

```js
const mergeResolvers = (target, input) => {
  const inputTypenames = Object.keys(input);
  const merged = inputTypenames.reduce(
    (accum, key) => {
      const inputResolver = input[key];
      if (target[key]) {
        const targetResolver = target[key];
        const resolvedInput = inputResolver();
        const resolvedTarget = targetResolver();
        if (
          !!resolvedTarget &&
          !!resolvedInput &&
          isDict(resolvedTarget) &&
          isDict(resolvedInput)
        ) {
          const newValue = { ...resolvedTarget, ...resolvedInput };
          return {
            ...accum,
            [key]: () => newValue,
          };
        }
      }
      return { ...accum, [key]: inputResolver };
    },
    { ...target }
  );
  return merged;
};
const buildSchema = mocks => {
  const schemaStr = print(schemaGQL) + clientDefs;
  const schema = makeExecutableSchema({
    typeDefs: schemaStr,
    resolverValidationOptions: {
      requireResolversForResolveType: false,
    },
  });

  return addMocksToSchema({ schema, mocks, preserveResolvers: true });
};

export const ApolloProviderWithMock = ({ customResolvers, client, children }) => {
  const mocks = mergeResolvers(globalMocks, customResolvers);
  const schema = buildSchema(mocks);

  let apolloClient = client;

  if (!client) {
    apolloClient = new ApolloClient({
      fetch,
      link: new SchemaLink({ schema }),
      cache: new InMemoryCache({ possibleTypes }),
      typeDefs: schema,
    });
  }

  return <ApolloProvider client={apolloClient}>{children}</ApolloProvider>;
};
```
Then in a test I just need to wrap the component being tested with it. Also, I can set specific values for specific queries
```js
const customerResolver = {
  Query: () => ({
    SomeQuery: () => ({
      [...]
    })
  })
}
<ApolloProviderWithMock customerResolver={customerResolver}>
  <Component>
</ApolloProviderWithMock>
```

**Comment by bryancuster** [comment]
I am actually unable to get `MockedProvider` working at all on any 3.x version of `@apollo/client`.

```js
import { render } from '@testing-library/react'
import '@testing-library/jest-dom/extend-expect'
import { MockedProvider } from '@apollo/client/testing'
import { Route, MemoryRouter } from 'react-router-dom'

...

describe('pipeline: none', () => {
  test('does not render environment section', async () => {
    const { getByText } = render(
      <MockedProvider
        mocks={[
          {
            request: {
              query: MARKETPLACE_OFFERING_QUERY,
              variables: {
                guid
              }
            },
            result: {
              data: {
                offering: { guid, name: 'mock offering' }
              }
            }
          }
        ]}
        addTypename={false}
      >
        <MemoryRouter initialEntries={['builder/123/456']}>
          <Route path="builder/:offering_guid/:plan_guid">
            <Builder />
          </Route>
        </MemoryRouter>
      </MockedProvider>
    )

    await new Promise(resolve => setTimeout(resolve, 0)) // wait for response

    expect(getByText('mock offering')).toBeInTheDocument()
  })
})
```

Leaving out this, the loading state is always true. With it the component is able to log out `loading: true` and then `loading: false`.
```js
    await new Promise(resolve => setTimeout(resolve, 0)) // wait for response
```

The assertion fails, data is always undefined in the component even when `loading: false` from the `useQuery`.

**Comment by Markus-ipse** [comment]
My team seem to have run into the same problem :(

**Comment by abFx** [comment]
Same here, the mock provider seems to stopped working in some cases while running the styleguidist server, and when generating the static version of the styleguidist, some cases do work. A bit unstable, and now we are currently deciding if we should revert, or look for a solution.

**Comment by Markus-ipse** [comment]
In my case it was the same problem as described here: https://github.com/apollographql/apollo-client/issues/6771

I added logging to my component that did the mutations and saw that the variables contained a field with an explicit `undefined` instead of omitting the field. So I just explicitly added `undefined` for the variable in my mock as well and it started working!

**Comment by emmanuelkant** [comment]
In my case I added the prop `addTypename={true}` and the error stoped. I realized that the error message was with the data with `__typename`. Like this:

```js
products {
  name
  description
  price
  __typename
}
```
So I tried this and worked for me. However, the error still is a mystery for me.

**Comment by aleksandr-omise** [comment]
Get this error - `No more mocked responses for the query: mutation`. Seems like `MockedProvider` broken or poorly documented.

**Comment by deltek-rossjackson** [comment]
I've resolved this with my post on this [one](https://github.com/apollographql/react-apollo/issues/1747#issuecomment-603444537)

```
defaultOptions={{
                                watchQuery: { fetchPolicy: 'no-cache' },
                                query: { fetchPolicy: 'no-cache' },
                            }}
```

**Comment by joshjg** [comment]
> In my case it was the same problem as described here: #6771
> 
> I added logging to my component that did the mutations and saw that the variables contained a field with an explicit `undefined` instead of omitting the field. So I just explicitly added `undefined` for the variable in my mock as well and it started working!

I found the issue to be the same as @Markus-ipse 

The change in behavior appears to have been introduced here, by switching to a different deep equal function: https://github.com/apollographql/apollo-client/commit/87c7a2bcc285626dd666587ab2c2b4103af161bc

The previous `isEqual` implementation ignored `undefined` object properties. Unfortunately, we were relying on that behavior so hundreds of our tests are now failing in 3.1.x.

**Comment by Hianz** [comment]
Is there any progress on this issue on getting it resolved?

**Comment by benjamn** [comment]
This behavior should be fixed/improved in `@apollo/client@3.3.0-beta.9` (just published to npm), thanks to #7108. Please give it another try after updating!

**Comment by AdrienLemaire** [comment]
Getting the same `No more mocked responses for the query` error.
Bumping to 3.3.0-beta.9 didn't resolve it.
Adding defaultOptions with fetchPolicy: "no-cache" didn't help either.

test:
```ts
describe("ProfileHeader", () => {
  it.only("show a profile header", async () => {
    const { container } = renderApollo(<ProfileHeader />, {
      defaultOptions: {
        query: { fetchPolicy: "no-cache" },
        watchQuery: { fetchPolicy: "no-cache" },
      },
    });
    await waitFor(() => {
      expect(container).toMatchSnapshot();
    });
  });
```

renderApollo
```tsx
import { MockedProvider, MockedResponse } from "@apollo/client/testing";

const renderApollo = (
  node: any,
  {
    mocks,
    addTypename,
    defaultOptions,
    cache,
    resolvers,
    ...options
  }: RenderApolloOptions = {}
): RenderResult => {
  return render(
    <MockedProvider
      mocks={mocks}
      addTypename={addTypename}
      defaultOptions={defaultOptions}
      cache={cache}
      resolvers={resolvers}
    >
      {node}
    </MockedProvider>,
    options
  );
};
```

Component:
```tsx
const ProfileHeader: React.FC = () => {
  const [queryExecutor, { loading, error, data }] = useLazyQuery<TMe>(
    PROFILE_QUERY,
    {
      // fetchPolicy: "cache-only", // <!== If changing the fetchPolicy here, the test pass!
      fetchPolicy: "cache-and-network",
      nextFetchPolicy: "cache-first",
    }
  );
```

It would seem like MockedProvider doesn't replace my useLazyQuery optiosn with the defaultOptions passed from the test.

**Comment by betweenparentheses** [comment]
Still experiencing this issue, even with setting fetchPolicy: no-cache in the defaultOptions for both watchQuery and query, even with using the new beta version. The Dog example from the docs fails on my environment with direct copy/paste. https://www.apollographql.com/docs/react/development-testing/testing/

**Comment by manukapoor** [comment]
>This behavior should be fixed/improved in @apollo/client@3.3.0-beta.9 (just published to npm), thanks to #7108. Please give it another try after updating!

This fixes my issue @benjamn , do we have any visibility into a release schedule? This is blocking our development and it'd be great to have an estimate. Thanks!

**Comment by btferus5** [comment]
I was having this issue on any 3.x.x version (my mocks have correct variables + __typenames and all that junk, this seemed like a legitimate bug with MockedProvider), upgrading to @apollo/client@3.3.0-beta.9 did NOT fix it for me, but upgrading to @apollo/client@3.3.0-beta.16 DID fix it for me. 

so I would suggest trying @apollo/client@3.3.0-beta.9

**Comment by mbrowne** [comment]
The current apollo-client release is 3.3.5, and this seems to be fixed now.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Comment by findlay-hannam** [comment]
I'm still getting this on version `3.3.21`

**Comment by mbrowne** [comment]
@findlay-hannam Are you running multiple queries in a single test? Maybe you actually need to add more mocks. (But it's also possible there's still a bug somewhere.)

**Comment by findlay-hannam** [comment]
I _am_ running multiple queries, but the tests pass when I set the fetchPolicy to 'no-cache'. I'm currently using the workaround @btferus5 suggested

**Comment by cheukribbon** [comment]
Have similar issue with fetchPolicy
