### ISSUE TITLE
Fetchingmore and notifyOnNetworkChange not working in 3.3.7

### ISSUE THREAD

**Issue by robertsmit** [apollographql/apollo-client#7607]
In the latest version the NetWorkStatus for fetchingMore changed. Earlier it was 7, now ready is 7:
```
export declare enum NetworkStatus {
    loading = 1,
    setVariables = 2,
    fetchMore = 3,
    refetch = 4,
    poll = 6,
    ready = 7,
    error = 8
}

```

But when fetchingMore, the networkStatus is never changed to 3....

**Comment by jcreighton** [comment]
@robertsmit Could you provide a runnable reproduction using either [this repo](https://github.com/apollographql/react-apollo-error-template) or [this CodeSandbox](https://codesandbox.io/s/condescending-fermi-07u2p)?

**Comment by sflahave** [comment]
I'm seeing the same ... I'm expecting that if a call to `fetchMore` triggers a network call, then either `loading` or `networkStatus` should be updated so I can let the user know that data is loading. 

I have a query setup like this: 

```
const { loading, error, data, fetchMore, networkStatus } = useQuery(ALL_JOBS, {
    variables: {
      filter,
      first: rowsPerPage,
      sortBy,
      sortDir,
    },
    notifyOnNetworkStatusChange: true,
    context: {
      debounceKey: "ALL_JOBS",
      debounceTimeout: 50,
    },
  })
```

Then I have a sort function that gets called when a user wants to change the sorting: 
```
function sort(propertyName) {
    const newSortBy = propertyName
    const newSortDir = propertyName !== sortBy ? "ASC" : sortDir === "ASC" ? "DESC" : "ASC"
    setSortBy(newSortBy)
    setSortDir(newSortDir)
    setPage(0)
    fetchMore({
      variables: {
        filter,
        first: rowsPerPage,
        sortBy: newSortBy,
        sortDir: newSortDir,
      },
    })
  }
```

I can see that this triggers a network call, but the `loading` always remains `false` and `networkStatus` always stays at 7.

**Comment by ramiAbdou** [comment]
I'm seeing the same issue. I'm using local-only fields in my query and when it changes and it is fetching from the network, it does not update the `loading` and `networkStatus` variables.

**Comment by chyamuna** [comment]
Any update on this. We are also facing the same issue.

**Comment by eyalw** [comment]
+1

**Comment by alex20465** [comment]
+1

Its always the same ===7

**Comment by drewlustro** [comment]
I don't believe this issue needs reproduction. The scenario described is pretty common, no?

**Comment by alaminut** [comment]
I'm having the same problem and came across this issue while searching and can't believe it's still open so I'll add my situation to the list too.

_Code is simplified for a better reading experience_

Given the query:

```
const query = gql`
  query fetchSomeData($skip: Int!, $take: Int!) {
    items(skip: $skip, first: $take) {
      id
      title
    }
}`
```

In my component:

```
const Component = () => {
  const skip = useRef(0);
  const {data, loading, fetchMore} = useQuery(query, {
    notifyOnNetworkStatusChange: true // having this does not make any difference
    variables: {
      skip: skip.current,
      take: 10
    }
  })

  return (
    <div>
      {loading && <Spinner />}
      {data.items.map(item => <ItemRenderer item={item} />)}
      <button onClick={() => fetchMore({ variables: { skip: skip.current + 10 } })}>Load more</button>
    </div>
  )
}
```

Clicking the button triggers the network request, and `data` gets updated but `loading` never changes. I have a very basic, naive array merge policy in the cache configuration like the one below:

```
typePolicies: {
  Query: {
          fields: {
            items: {
              keyArgs: false,
              merge(existing = [], incoming) {
                return [...existing, ...incoming];
              },
            },
          },
        }
}
```

If I remove the field policy then I need to provide a similar _merge policy_ in the `updateQuery` parameter of `fetchMore` but regardless the `loading` field from the `useQuery` result never gets updated.

**Comment by dhmcloud** [comment]
Also, just wanted to add that I am seeing the same behaviour as mentioned by @alaminut

**Comment by bhavikagrawal** [comment]
[This](https://github.com/apollographql/apollo-client/issues/6354#issuecomment-664879778) should solve the issue.

**Comment by miladdotnetdeveloper** [comment]
> [This](https://github.com/apollographql/apollo-client/issues/6354#issuecomment-664879778) should solve the issue.

Unfortunately it didn't solve the problem for me. I don't set the query and have the same problem. My code is like below:

```
const handleLoadMoreClick = () => {
    setLoadMoreLoading(true);
    const endCursor = data?.liveData?.pageInfo.endCursor;
    fetchMore({
      variables: { after: endCursor },
      updateQuery: (previousQueryResult, { fetchMoreResult }) => {
        if (!fetchMoreResult.liveData) return previousQueryResult;
        fetchMoreResult.liveData.edges = [
          ...(previousQueryResult.liveData?.edges?.map((x) => x) ?? []),
          ...(fetchMoreResult.liveData.edges ?? []),
        ];
        setLoadMoreLoading(false);
        return fetchMoreResult;
      },
    });
  };
```

I use **"@apollo/client": "^3.6.6"**

**Comment by bhavikagrawal** [comment]
> > [This](https://github.com/apollographql/apollo-client/issues/6354#issuecomment-664879778) should solve the issue.
> 
> Unfortunately it didn't solve the problem for me. I don't set the query and have the same problem. My code is like below:
> 
> ```
> const handleLoadMoreClick = () => {
>     //setLoadMoreLoading(true);
>     const endCursor = data?.liveData?.pageInfo.endCursor;
>     fetchMore({
>       variables: { after: endCursor },
>       updateQuery: (previousQueryResult, { fetchMoreResult }) => {
>         if (!fetchMoreResult.liveData) return previousQueryResult;
>         fetchMoreResult.liveData.edges = [
>           ...(previousQueryResult.liveData?.edges?.map((x) => x) ?? []),
>           ...(fetchMoreResult.liveData.edges ?? []),
>         ];
>         //setLoadMoreLoading(false);
>         return fetchMoreResult;
>       },
>     });
>   };
> ```
> 
> The commented lines are a workaround for setting loading state for a button. I use **"@apollo/client": "^3.6.6"**

Did you use notifyOnNetworkStatusChange: true ?

**Comment by SimplySayHi** [comment]
I'm having the same issue.
Setting notifyOnNetworkStatusChange to true doesn't solve it.
After ajax call ends, the values of loading and networkStatus are always set to true and 3 ( fetchMore ) respectively.

**Comment by miladdotnetdeveloper** [comment]
> > > [This](https://github.com/apollographql/apollo-client/issues/6354#issuecomment-664879778) should solve the issue.
> > 
> > 
> > Unfortunately it didn't solve the problem for me. I don't set the query and have the same problem. My code is like below:
> > ```
> > const handleLoadMoreClick = () => {
> >     //setLoadMoreLoading(true);
> >     const endCursor = data?.liveData?.pageInfo.endCursor;
> >     fetchMore({
> >       variables: { after: endCursor },
> >       updateQuery: (previousQueryResult, { fetchMoreResult }) => {
> >         if (!fetchMoreResult.liveData) return previousQueryResult;
> >         fetchMoreResult.liveData.edges = [
> >           ...(previousQueryResult.liveData?.edges?.map((x) => x) ?? []),
> >           ...(fetchMoreResult.liveData.edges ?? []),
> >         ];
> >         //setLoadMoreLoading(false);
> >         return fetchMoreResult;
> >       },
> >     });
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The commented lines are a workaround for setting loading state for a button. I use **"@apollo/client": "^3.6.6"**
> 
> Did you use notifyOnNetworkStatusChange: true ?

Thank you for reply, I set the option `notifyOnNetworkStatusChange: true` in `useQuery` and it seems `networkStatus != NetworkStatus.loading` is reliable now.

**Comment by bhavikagrawal** [comment]
> I'm having the same issue. Setting notifyOnNetworkStatusChange to true doesn't solve it. After ajax call ends, the values of loading and networkStatus are always set to true and 3 ( fetchMore ) respectively.

loading will always result to true for fetchmore, therefor you need to use networkStatus to toggle your loading state.

**Comment by fridaystreet** [comment]
> [This](https://github.com/apollographql/apollo-client/issues/6354#issuecomment-664879778) should solve the issue.

Awesome thanks, this worked for us, we were passing the query property to fecthMore. removed it and voila!

**Comment by kmgdevelopment** [comment]
I'm still having this issue in version 4.1.6. I'm not passing the query property to `fetchMore` and I have `notifyOnNetworkStatusChange` set to `true`. `networkStatus` always returns `7` after the initial load and `loading` is always `false`.

**Comment by jerelmiller** [comment]
@kmgdevelopment do you have a reproduction you can share? We have quite a few tests that show `networkStatus` and `loading` set appropriately when calling `fetchMore` so its difficult to understand what the root cause is without something we can play around with.

Here is an example with `useQuery` where you can see that after calling `fetchMore`, the `networkStatus` and `loading` value is set correctly:

https://github.com/apollographql/apollo-client/blob/98439d701e0bdc6ac462c7c886988488570fa29c/src/react/hooks/__tests__/useQuery.test.tsx#L4945-L5021

A reproduction would go a long way to understand what you're seeing. Thanks!

**Comment by kmgdevelopment** [comment]
Here you go: https://codesandbox.io/p/devbox/dreamy-noether-jz3cmh

The meat of it is in `app/components/recipe-entries-list.tsx`. `fetchMore` is called when the pager element triggers the intersection observer. On line 64 the pager should disappear when `networkStatus` is `3`, but that doesn't seem to be happening.

**Comment by jerelmiller** [comment]
Thanks so much @kmgdevelopment! I'll do my best to look at this when I get some free time.

**Comment by jerelmiller** [comment]
@kmgdevelopment is there any chance you can isolate the reproduction to just `@apollo/client`? I see your reproduction uses the Next.js integration so there is a chance this might be related to the integration package itself. If you can narrow down whether you see this behavior in the core package, or whether it shows itself with the Next.js integration, that would be greatly appreciated. Thanks!

**Comment by kmgdevelopment** [comment]
@jerelmiller Sure, I set it up with the Next.js pages router. Codesandbox decided to stop authenticating me so [here's a repo you can clone](https://github.com/kmgdevelopment/Apollo-Client-fetchMore-Demo).
