### ISSUE TITLE
Query not being cleaned up when on Strict Mode

### ISSUE THREAD

**Issue by PierreAndreis** [apollographql/apollo-client#8011]
**Intended outcome:**
When unmounting a component that uses `useQuery`, it should clean up even when wrapped by Strict Mode.

**Actual outcome:**
Updating the cache on which an unmount component depends, generates a react warning about memory leak.

**How to reproduce the issue:**
https://codesandbox.io/s/nifty-heyrovsky-5cf34
1- Click on "John Smith" and wait for the page to load
2- Click on "Back"
3- Click on "Like" button right by "John Smith"
4- Observe the warning in the console.

Checking on Apollo DevTools, there seems to be more active queries than it should have been after a few times reproducing the issue.
![image](https://user-images.githubusercontent.com/5843816/115635350-5ea19380-a2c0-11eb-9ff9-c5373004d042.png)
Compared to when Strict mode is not active:
![image](https://user-images.githubusercontent.com/5843816/115635471-a0323e80-a2c0-11eb-8ece-d4a16bc4c02f.png)
**Versions**
```
@apollo/client: 3.3.15
graphql: 15.4.0
react: 17.0.2
react-dom: 17.0.2
react-router-dom: 5.2.0
```

**Comment by PierreAndreis** [comment]
Note that this doesn't happen in production build, when strict mode is noop.

**Comment by PierreAndreis** [comment]
Might be related to https://github.com/apollographql/apollo-client/pull/7952#issuecomment-814329144

**Comment by bmviniciuss** [comment]
Having the same issue on Strict mode. But i'm also getting the `Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all` error.

```json
"dependencies": {
    "@apollo/client": "^3.3.17",
    "graphql": "^15.5.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-router-dom": "^5.2.0",
    "typescript": "^4.1.2",
    "vite": "^2.3.0"
  }
```

![image](https://user-images.githubusercontent.com/20448523/118073422-2e5e8980-b382-11eb-9fdd-1bba1939b561.png)
![image](https://user-images.githubusercontent.com/20448523/118073459-3dddd280-b382-11eb-93ec-b41dd53c2b3c.png)

**Comment by 6axter82** [comment]
Having this warnings in "@apollo/client": "^3.3.19"

**Comment by hwillson** [comment]
This should be fixed with `@apollo/client` >= 3.4 - thanks!

**Comment by Ralino** [comment]
While the warning is gone, I still have the issue that the queries are not cleaned up with `@apollo/client` 3.4.8 when strict mode is enabled, as shown in this demo: https://codesandbox.io/s/nostalgic-solomon-4stu5

Looking at the active queries with the dev tools, it seems like a query is spawned twice, one with "__typename" queried as well and one without. But only the query with "__typename" is cleaned up. Without strict mode, only a query with "__typename" is spawned (and cleaned up).

**Comment by hjrobinson** [comment]
I just wanted to note here for anyone using react-router's history to navigate to another page after deleting a document that the memory leak warning went away when I updated to  the latest version of @apollo/client (for me this was  "@apollo/client": "^3.5.10"). I was previously using version 3.1.4. I needed to restart my application for this to take effect.
