### ISSUE TITLE
Typescript error when ignoring errors

### ISSUE THREAD

**Issue by alexpuertasr** [apollographql/apollo-client#8896]
**Intended outcome:**
Following the documentation I want to ignore the errors and handle the issue with any typescript issue:
https://www.apollographql.com/docs/react/data/error-handling/#ignoring-errors

**Actual outcome:**
The code is working well but I have a typescript error:
`Type 'null' is not assignable to type 'readonly GraphQLError[] | undefined'.`

**How to reproduce the issue:**
Ignore the error like it's documented here using typescript:
https://www.apollographql.com/docs/react/data/error-handling/#ignoring-errors

**Versions**
System:
    OS: macOS 11.5.2
Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
Browsers:
    Chrome: 94.0.4606.61
    Firefox: 86.0.1
    Safari: 14.1.2
npmPackages:
    @apollo/client: 3.4.15 => 3.4.15

**Comment by brainkim** [comment]
This might have been fixed by https://github.com/apollographql/apollo-client/pull/8424, which was shipped in 3.5, which is currently in an RC phase. Can you try installing `@apollo/client@beta`?

**Comment by alexpuertasr** [comment]
Hi @brainkim, I tried the latest beta (@apollo/client: 3.5.0-rc.1) but it's still happening. I prepared a codesandbox so you can see this by your own:

https://codesandbox.io/s/typescript-error-gtmnm?file=/src/apolloClient.ts

**Comment by schw4rzlicht** [comment]
I am stumbling across the same issue. I am on `@apollo/client@3.5.7`. Any news on this?
