### ISSUE TITLE
Possible stale data within additional re-render loops by useQuery in v3.5.x

### ISSUE THREAD

**Issue by transcranial** [apollographql/apollo-client#9135]
When a query variable changes, it appears to take an additional render loop to be reflected in the query results. This creates situations where the data does not match the variable, without any changes in loading or network state.

This is new behavior compared to v3.4.17.

The relevant lines from the repro below:

```jsx
  const [name, setName] = useState('');
  const {
    loading,
    data,
    variables,
  } = useQuery(ALL_PEOPLE, { variables: { name } });
  console.log(name, variables.name);
```

**Intended outcome:**

To see previous behavior in v3.4.17: `npm install @apollo/client@3.4.17 graphql@^15`. Enter text in the input field and observe the console log, for example, `abcd`:

```
a a
ab ab
abc abc
abcd abcd
```

**Actual outcome:**

See repo linked below for behavior in v3.5.x. The same action produces:

```
a 
a a
ab a
ab ab
abc ab
abc abc
abcd abc
abcd abcd
```

**How to reproduce the issue:**

https://github.com/transcranial/apollo-client-issue-repro

[relevant lines](https://github.com/transcranial/apollo-client-issue-repro/blob/main/src/index.jsx#L114-L120)

**Versions**

```
  System:
    OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  npmPackages:
    @apollo/client: ^3.5.5 => 3.5.5 
```

**Comment by brainkim** [comment]
@transcranial Thank you for the report. I updated the title based on what I think you’re describing. Let me know if this description is inaccurate.

To be honest, I’m not sure how to fix this without going back to some kind of side-effect in the render function hack, although I’m very happy to break React rules at this point. Did this new behavior cause problems for you or is this a theoretical possible bug?

**Comment by dmarkow** [comment]
@brainkim We are having a real world issue due to this, not theoretical. And it's not just the `variables` not getting updated, it looks like the whole object returned by `useQuery` after a variable change is stale.

```typescript
const [search, setSearch] = useState('');
const { loading, data, variables } = useQuery(query, { variables: { search } });

// If we searched and there is only one result, just redirect to that result
if (!loading && search && data.projects.length === 1) {
  return <Redirect to=... />;
}

// If there is no search term, display a list of projects, even if there is just one
...
```

In 3.4.x, calling `setSearch` updates `search`, sets `loading` to true, and `variables` has the new search term in it, all in the same render.

As of 3.5.x, it sets `search` to my query, but the useQuery object stays the same on the next render, with `loading` false and `variables` not containing my search query. Then it immediately re-renders with `loading` true and `variables` containing my query. However, since we're detecting on a combination of `loading` and `search`, it redirects before it has a chance to complete the query.

We can work around this by checking `!loading && variables.search` instead of `!loading && search`, but this still seems like a regression with the unnecessary render where `loading` stays false?

**Comment by transcranial** [comment]
@briankim I think my original title was accurate, because as @dmarkow points out, it's everything returned by `useQuery`, not just `variables`. I used `variables` in my report to illustrate the additional render loops generated in 3.5.x.

This definitely caused real problems for us. @dmarkow gave a good example: in this case,`data` and `search` will be out-of-sync for one render loop.

**Comment by brainkim** [comment]
Thanks for the report. Fixed by ^ this commit but I have yet to come with a unit test that fails.

**Comment by dmarkow** [comment]
I see 3.5.6 released with a fix for useQuery variables. However, the issue is still happening on 3.5.6. The query's variables *are* being updated now without being out of sync, but loading still stays false for one render. If we change the variables, shouldn't the loading state immediately be true, like it was in 3.4.x?

Put another way, here are the different values returned by useQuery that trigger renders in each version:

```
// 3.4.17 renders twice. This seems like the correct number of renders.
{ loading: true, variables: { search: "hello" } }
{ loading: false, variables: { search: "hello" }, data: ... } // data has new results

// 3.5.5 renders three times
{ loading: false, variables: { search: undefined }, data: ... } // data is the old/stale data, variables aren't updated
{ loading: true, variables: { search "hello }, data: ... }
{ loading: false, variables: { search: "hello" }, data: ... } // data has new results

// 3.5.6 renders three times
{ loading: false, variables: { search: "hello" }, data: ... } // data is the old/stale data. Variables are now correct in 3.5.6, but still does this unnecessary loading: false render loop
{ loading: true, variables: { search "hello }, data: ... }
{ loading: false, variables: { search: "hello" }, data: ... } // data has new results

```

**Comment by kainosnoema** [comment]
> However, the issue is still happening on 3.5.6. The query's variables _are_ being updated now without being out of sync, but loading still stays false for one render. If we change the variables, shouldn't the loading state immediately be true, like it was in 3.4.x?

We're also seeing this with 3.5.6. Until this is resolved and behavior reverted back to what's in 3.4.x (and what you would expect), we'll be holding off upgrading.

**Comment by yevhen-logosha** [comment]
Glad we also catch it before pushing to prod. At first everything seem to work, but that one place is broken. Hoping for a fix. 
You guys are doing **tremendous** job no doubt, only thing is that in semantic versioning we trust 🙏 and not expecting something breaking from a non-major release 🙈 
But again, your work is hugely appreciated nevertheless ! 💪

**Comment by dmarkow** [comment]
This seems to be fixed with the new 3.6.0 release.
