### ISSUE TITLE
TypeError:  _client is not a constructor

### ISSUE THREAD

**Issue by AdimAnyvision** [apollographql/apollo-client#9230]
**Intended outcome:**
When running tests in a React app, tests should run and @apollo/client package and it's utils should be recognized by jest and the tests should run.

**Actual outcome:**
When I update '@apollo/client' npm package to 3.4.16 or above, the tests for any compoennt that uses useQuery, useMutation, etc. fail to run due to the following error: 'TypeError: _client.InMemoryCache is not a constructor' 

![A1D360CD-6356-4549-BD08-98C574689406_4_5005_c](https://user-images.githubusercontent.com/88499398/146925198-7a48d87c-1f65-4307-9534-6c5e8e288992.jpeg)

However, when I use the previous version 3.1.3 the tests run successfully. 
It's important to note that each import in '@apollo/client' fails to run due to this problem (ApolloClient, InMemoryCache, HttpLink).

Added the init file for apollo client in the app:
```
import { ApolloClient, InMemoryCache, HttpLink } from '@apollo/client'
import { onError } from '@apollo/client/link/error'
import store from '../store'
import { performLogout } from '../store/actions/user'

const { gatewayFullPath, gatewayPrefix } = window.Config
const unauthorizedStatus = [401]
const SERVICES_PREFIX = 'api'

const cache = new InMemoryCache({
  addTypename: false
})

const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'no-cache'
  }
}

const httpLink = new HttpLink({
  uri: `${ gatewayFullPath }/${ gatewayPrefix }/${ SERVICES_PREFIX }/graphql`
})

const logoutLink = onError(({ networkError }) => {
  if (networkError && unauthorizedStatus.includes(networkError.statusCode)) {
    store.dispatch(performLogout())
  }
})

const client = new ApolloClient({
  cache,
  link: logoutLink.concat(httpLink),
  defaultOptions
})

export default client
```

'TypeError' errors are ussualy due to wrong import (like default import instead of regular one)

**How to reproduce the issue:**
Update '@apollo/client' version to latest and run tests 'npm test'

**Comment by hwillson** [comment]
@AdimAnyvision the issue you're encountering doesn't seem to be very common. Please provide a small runnable reproduction demonstrating this problem and we'll take a closer look.

**Comment by jzaynal** [comment]
We're also facing this issue. I think it's this one that was fixed previously that may have come back: https://github.com/apollographql/apollo-client/issues/8816

Locking `@apollo/client` to version `3.4.13` has my Jest tests all passing fine, changing to latest version (`3.5.6` as of writing this) with no code change and tests are failing with `TypeError: _client.InMemoryCache is not a constructor`

It's the same with everything imported from `@apollo/client`. When logging it out in my tests I get `undefined` for `ApolloClient`, `InMemoryCache`, and anything else I import from the package.

**Comment by AdimAnyvision** [comment]
Thanks for letting me know @jzaynal !
I have the exact error as you have written.

Is there a reason why the same error came back?

**Comment by jzaynal** [comment]
I don't know for the reason but given that the error may be due to circular dependency and how imports are done, I'm guessing changes since `3.4.13` must've introduced an import line that causes circular dependency again.

**Comment by saimonmoore** [comment]
I've tried both 3.5.7 and 3.4.13 and I'm still getting the exact same error as https://github.com/apollographql/apollo-client/issues/8816#issuecomment-949715608. Very frustrating.

**Comment by solarmosaic-colin-young** [comment]
Just wanted to add that I'm also noticing this on 3.5.8.

**Comment by mponce2-chwy** [comment]
@AdimAnyvision 

Were you able to find a solution?

**Comment by moises-cp** [comment]
> @AdimAnyvision the issue you're encountering doesn't seem to be very common. Please provide a small runnable reproduction demonstrating this problem and we'll take a closer look.

@hwillson 

Example code from [Configuring the Apollo Client cache > Initialization](https://www.apollographql.com/docs/react/caching/cache-configuration#initialization)

```javascript
import { InMemoryCache, ApolloClient } from '@apollo/client';

const client = new ApolloClient({
  // ...other arguments...
  cache: new InMemoryCache(options)
});
```


Let say you have a React file where the Apollo cache is setup following the code above. When you run a Jest unit test against this file, the TypeError below will be thrown.  

<img width="537" alt="image" src="https://user-images.githubusercontent.com/17182683/163414168-95204eb5-0110-4ace-8fa9-6e0e2fd19872.png">

Any idea why this is happening?
