### ISSUE TITLE
Queries hang and are not issued on network requests

### ISSUE THREAD

**Issue by andreialecu** [apollographql/apollo-client#9690]
**Intended outcome:**

Queries should be dispatched to the network.

**Actual outcome:**

Queries are not dispatched to the network, they just hang.

While using `apollo-angular@3.0.1` with `@apollo/client@3.6.x` it appears that some queries start hanging after a while. 

I'm also using graphql-code-generator to generate an apollo-angular data service, so usage looks like this:

```ts
this.someQuery
      .fetch({
        myVariable: 1
      })
      .pipe(map((res) => res.data.someQuery))
      .subscribe(foo => console.log(foo));
```

After a while (within 1-2 minutes), the subscribe block will not be called any more. This can also be used with `rxjs`'s `await firstValueFrom(...)` and the promise will never resolve.

Downgrading to ~~3.6.2~~ 3.5.10 seems to fix the problem.

**How to reproduce the issue:**

Unfortunately no repro, but hopefully it might be easy to pinpoint what would affect these by comparing ~~3.6.2 to 3.6.3.~~ 3.6.0 and 3.5.10.

**Versions**
```
System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.0-git.20220329.hash-0764215 - ~/.nvm/versions/node/v16.14.2/bin/yarn
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.4
  npmPackages:
    @apollo/client: 3.6.3 => 3.6.3
    apollo-angular: ^3.0.1 => 3.0.1 
    apollo-link-scalars: ^4.0.1 => 4.0.1
```

**Comment by andreialecu** [comment]
FWIW, we're also using `HttpBatchLink` from `apollo-angular` and the default options are:
```ts
  const defaultOptions = {
    watchQuery: {
      fetchPolicy: 'no-cache',
      errorPolicy: 'ignore',
    },
    query: {
      fetchPolicy: 'no-cache',
      errorPolicy: 'all',
    },
  };
```

`no-cache` queries are definitely affected, we only have a few cached ones in this project and I cannot confirm if they're also affected or not at this point.

**Comment by benjamn** [comment]
@andreialecu Do you think you could put together a small runnable [reproduction](https://github.com/apollographql/react-apollo-error-template) reproducing the regression? Or open a PR with a failing test (no need to fix it; we will investigate)?

**Comment by andreialecu** [comment]
@benjamn the only change I see in 3.6.3 that could impact apollo-angular in any way is the one from this commit: https://github.com/apollographql/apollo-client/commit/77119b06b165dbcb02d8ea7aeef17a12a08d059c

I'm not sure if I'll be able to reproduce it in isolation since it's random when it starts happening and I'm not sure if it's a race condition of some sort with the batching link. But I will try to investigate further.

**Comment by benjamn** [comment]
Let's keep the discussion here (not twitter) please!

You can test your theory about that commit by running these commands locally:
```sh
git clone git@github.com:apollographql/apollo-client.git
cd apollo-client
git revert 77119b06b165dbcb02d8ea7aeef17a12a08d059c
npm run build
cd dist
npm pack
cd ..
```
That will give you a `.tgz` bundle that you can install locally in your application:
```sh
cd ~/path/to/your/app
npm i ~/path/to/apollo-client/dist/apollo-client-3.6.3.tgz
```
Hope that helps with your investigation (or at least is easier than creating a reproduction)!

**Comment by andreialecu** [comment]
@benjamn somehow I'm not able to reproduce this early today, so I'm very confused.

Yesterday it was reproducible every single time in production, staging and development - but it was occurring during peak times.

We use graphql subscriptions and there's a lot of chatter over them, that's the only thing that could be relevant. One of the subscriptions then triggers a query on a certain condition. 

I'll try to reproduce it during the next peak.

The problems cleared up for all of our customers after deploying a downgrade to 3.4.17 initially as per my comment in https://github.com/apollographql/apollo-client/issues/9456#issuecomment-1119942293

I've then tried upgrading up until 3.6.2 and I couldn't reproduce it. On 3.6.3 it was reproducible again. 

Peak times were fading by that point, so it might be possible the problem isn't exactly between 3.6.2 and 3.6.3 but could be earlier. I'll continue monitoring this over the next few days.

**Comment by andreialecu** [comment]
I have an update. 

It appears this also happens on 3.6.2 (deployed it in production earlier) so is not a recent regression in 3.6.3. 

It seems to be related to peak times somehow (a lot of subscriptions chatter at least).

I have reverted to 3.4.17 for now where everything seems fine. I haven't yet checked 3.5.x.

Since this happens in apollo angular I assume it's an issue in the core and not the react part.

**Comment by andreialecu** [comment]
@benjamn another update. I've been troubleshooting this today and setting breakpoints once it started happening.

Seems when it hangs it starts hitting this line of code:

<img width="741" alt="Screenshot 2022-05-07 at 21 18 22" src="https://user-images.githubusercontent.com/697707/167266843-357f9c1f-4cfc-449d-b08f-d7eca042d35c.png">

But the error is swallowed somewhere and is never thrown. I'm not sure if it's apollo-angular hiding it.

This is with 3.6.2

I found #7608 which seems related.

**Comment by andreialecu** [comment]
The reason it's probably swallowed is that `sub` ends up being `null` here:

<img width="871" alt="Screenshot 2022-05-07 at 21 32 30" src="https://user-images.githubusercontent.com/697707/167267280-b166d6c0-0ed8-4f5a-811b-21720143585d.png">

**Comment by andreialecu** [comment]
I tracked this down further and it seems to be caused by various rxjs observables interacting with each other and restarting some subscriptions as a side-effect. Seems to be similar to what has been reported in this comment: https://github.com/apollographql/apollo-client/issues/7608#issuecomment-1090563931

Notice the screenshot for a stack trace:
<img width="633" alt="Screenshot 2022-05-07 at 21 41 37" src="https://user-images.githubusercontent.com/697707/167267623-6105fd69-f544-4eff-8912-a40e176a76d9.png">

`setCurrentClub` looks like this, essentially pushing a new value into an rxjs `ReplaySubject`:

<img width="450" alt="Screenshot 2022-05-07 at 21 42 38" src="https://user-images.githubusercontent.com/697707/167267634-69956bee-283a-4c0e-ab7d-435fa90a43b9.png">

This ends up cascading through various observables and tearing down and restarting a `watchQuery` somewhere.

**Comment by andreialecu** [comment]
Actually the plot thickens. 

I've changed some things so that those observables don't resubscribe. This prevented the "Observable cancelled prematurely" from happening, but the queries still hang. 🤔

**Comment by andreialecu** [comment]
Update: in `QueryManager`, `getObservableFromLink` seems to have the stuck query in `inFlightLinkObservables_1` and because of deduplication is not issued any more. 

I think that's what's causing the issue.

<img width="910" alt="Screenshot 2022-05-07 at 22 40 45" src="https://user-images.githubusercontent.com/697707/167269375-d86b61c7-3617-4000-8a7f-1691bc279f74.png">

Now as to why it gets stuck there, will need to investigate further.

**Comment by andreialecu** [comment]
So it appears that there's a callback being added to `concast.cleanup()` that is supposed to remove the observable from that `inFlightLinkObservables` map.

I think it's not being called most likely due to a race condition/or teardown situation similar to the one causing the "Observable cancelled prematurely" error.

The problem seems to be related to `Concast` not cleaning up properly:

Possibly relevant:
https://github.com/apollographql/apollo-client/blob/da3355ce794e105ad7f2652595fc33527a8a461b/src/core/QueryManager.ts#L991-L996

https://github.com/apollographql/apollo-client/blob/da3355ce794e105ad7f2652595fc33527a8a461b/src/core/QueryManager.ts#L1159-L1165

I can reproduce it consistently, if it would help to set up a screen sharing session at some point feel free to DM me on Twitter.

**Comment by andreialecu** [comment]
One other relevant thing. When this starts happening, in `QueryManager`, there's a memory leak and all of these stuck queries remain in this `queries` map:

<img width="535" alt="Screenshot 2022-05-08 at 12 36 23" src="https://user-images.githubusercontent.com/697707/167290393-87d6b0ff-cef4-4e4a-b0b6-29808288ae79.png">

**Comment by andreialecu** [comment]
I tried various versions, I wasn't able to reproduce this on `3.5.10` but it reproduces starting on `3.6.0`.

**Comment by andreialecu** [comment]
@benjamn if you have any suggestions which commits I could revert from `3.6.0` to try to isolate this, let me know, and I'll do it ASAP.

**Comment by benjamn** [comment]
Using your findings (thanks!), I was able to eliminate the `Observable cancelled prematurely` error, in favor of a quieter form cancellation/completion: #9701

**Comment by benjamn** [comment]
@andreialecu Quick way to test:
```
npm i @apollo/client@next
```
That will install `3.7.0-alpha.3`, which includes #9701. I believe these changes will be safe to release in 3.6.4, rather than waiting for v3.7, but it's a little easier to test on branch `release-3.7` before publishing/burning the 3.6.4 version.

**Comment by andreialecu** [comment]
@benjamn unfortunately the bug in the OP still exists in `3.7.0-alpha.3`

<img width="675" alt="Screenshot 2022-05-10 at 02 21 46" src="https://user-images.githubusercontent.com/697707/167514008-e36fd0b6-0850-41f8-8508-c4fcd45485a0.png">

Notice how `observable` contains somethin, is deduplicated and not issued.

As mentioned previously, the issue started between `3.5.10` and `3.6.0` but there are too many commits for me to be able to pinpoint one easily. So if you have any clue which one might've touched anything in this area, please let me know so I can try reverting it.

**Comment by patrickxrivera** [comment]
I noticed the same issue in `3.6.0` and downgraded to `3.5.10` which fixed it for me

**Comment by benjamn** [comment]
@andreialecu Are those 41 stuck queries all the queries you've sent through `getObservableFromLink`, or only some? Did any queries get successfully removed from that `concast.observers` set by the `concast.cleanup` function?

**Comment by andreialecu** [comment]
Once the bug starts happening any subsequent queries with the exact same variables get stuck. 

They're never removed and none of the promises/observables for that specific query ever resolve. 

I have one particular query where I can reproduce it very easily (because it is issued very frequently). But I have seen it hang for other queries as well.

**Comment by andreialecu** [comment]
Oh. And when a certain query is stuck, other ones will work fine. Or even the same query but with different variables. 

For more context about the business logic: 
- a subscription notifies that something changed
- we issue a query like `{ after: lastSeen }` which works for a bit but then gets stuck
- subscriptions keep coming in and issue the same query above with the same variables but they're all stuck in a queue behind each other due to deduplication

**Comment by benjamn** [comment]
Does it help (or change anything) to disable the deduplication?
```ts
new ApolloClient({
  queryDeduplication: false,
})
```

**Comment by andreialecu** [comment]
With deduplication disabled, the initial query may still get stuck randomly, but subsequent ones will go through even if they use the same variables.

They're still leaking and getting stuck here in `inFlightLinkObservables`:
<img width="311" alt="Screenshot 2022-05-11 at 15 47 52" src="https://user-images.githubusercontent.com/697707/167853310-6d0676ff-bed5-4212-8371-4cfbdc80cded.png">

However, because some queries are still getting stuck, this causes all sorts of issues.

**Comment by benjamn** [comment]
@andreialecu Can you try `npm i @apollo/client@beta` again (to get `3.7.0-alpha.4` this time)? That release includes #9718, which I am hopeful may be related to the issues you're having.

**Comment by bentron2000** [comment]
I am also having this issue. 

Some queries hang are never dispatched with `3.6.*` - but only when using `BatchHttpLink` - the issue does not occur when using 'HttpLink'
Just tried `3.7.0-alpha.5` - no joy.

Last version I can get to work with my `BatchHttpLink` setup is `3.5.10`

Don't have time to put together a repro - also it seems intermittent - but can answer questions if it helps...

**Comment by andreialecu** [comment]
Yep, I'm using batching, see my comment above. I'm using `HttpBatchLink` from `apollo-angular`, here's its implementation: https://github.com/kamilkisiela/apollo-angular/blob/master/packages/apollo-angular/http/src/http-batch-link.ts

> I'm not sure if I'll be able to reproduce it in isolation, since it's random when it starts happening. It could be a race condition of some sort with the batching link. I will try to investigate further.

**Comment by bentron2000** [comment]
> @andreialecu Are you also using `BatchHttpLink` by any chance?
> 
> @bentron2000 Even if `BatchHttpLink` is not involved in the original issue, I think that still merits investigation, possibly in a new issue.

I'm using React fwiw.

I'll watch and see what happens rather than clogging things up with a new issue for now. Will keep watching and commenting on solutions tho.

**Comment by doflo-dfa** [comment]
wow i'm glad I found this I was starting to think I was going insane 😄  useLazyQuery is hanging for us as well while using the most recent alpha-6

**Comment by doflo-dfa** [comment]
> wow i'm glad I found this I was starting to think I was going insane 😄 useLazyQuery is hanging for us as well while using the most recent alpha-6

I don't think what we were experiencing is a bug but a side effect of the change ... I appears I was not using useLazyQuery correctly in relation to my centralized contextProvider which oddly worked before the switch to 3.6.2+ and the alphas ... we switched to alpha-6 to solve the `Observable cancelled prematurely` (in production only) against react 18.1.0  ... once we did all lazy queries hung ... never executing whilst using useLazyQuery  (our queries that used useQuery worked just fine) 

After re-ordering some things on my end to a HLC context provider ... requests started happening again but alpha-2 ( i had downgraded until useLazyQuery worked again ) was returning partial results on the first handful of queries ... eventually completing after subsequent runs, almost like it was returning early ditching out of data recieve ( cache issues ? ) ... after re-upgrading to alpha-6 everything started working correctly, which is good because now I can sleep again.

**Comment by jdmoody** [comment]
I also have hanging queries as described in this issue. Some details:
- I'm upgrading from `3.2.2` to `3.6.5` (other issues prevent me from upgrading to versions between 3.2 and 3.6)
- I had the same issue with `3.7.0-alpha.4`
- I'm currently using React 18 in legacy mode with v3.2.2 without any issues
- I'm using `BatchHttpLink` and the issue goes away when I replace `BatchHttpLink` with apollo client's `HttpLink`
- It seems to always be the last `useQuery` call made that hangs (I can go into more detail about how I measured this if helpful).

This has been especially hard to debug because I haven't been able to reproduce it in a dev environment. I'm only able to reproduce it when deploying my app to a production-like environment. Then, when I try to attach a debugger to the box, I'm no longer able to reproduce it 😵

Afaict, this is the only issue blocking me from upgrading to v3.6, which is the only thing blocking me from using certain React 18 features.

It's also unclear to me whether all the behaviors described by folks in this issue are indeed the same issue. If it would be helpful for me to create a separate issue, or if there's any other info I can provide, please let me know 🙏🏻

**Comment by benjamn** [comment]
@jdmoody I appreciate all the details, and while I share your uncertainty about how many different issues we're talking about here, I think there must be something wrong with `BatchHttpLink`, probably a bug that's been there for a while but was only revealed by other changes recently, so that's what I'm currently looking into.

**Comment by vieira** [comment]
Hello, I have tried 3.6.6 which potentially resolves a possible cause for this issue (#9718) but after some testing the issue is still present.

As everyone else, we are also using `BatchHttpLink` and the last version that is working without this issue for us is 3.5.10.

**Comment by andrew-hu368** [comment]
I am not sure if it is related. We've recently upgraded from apollo v2 to apollo v3 (latest version). If I import the old ```BatchHttpLink``` from ```apollo-link-batch-http``` the queries are successfully run, while the new version causes some issues.

**Comment by jdmoody** [comment]
I did some testing on `@apollo/client@3.7.0-beta.3` and I can no longer reproduce the hanging queries  🙌🏻 

Thanks Ben!

**Comment by andreialecu** [comment]
Can also confirm that beta.3 seems to work.

I just changed to `beta.0` to verify that I can still repro the error and I could very quickly. 

Then upgraded to `beta.3` and I wasn't able to reproduce it, at least not within a few minutes of testing - by that point it would definitely happen with previous versions.

Seems fixed. Feel free to close the issue after releasing it to stable, or at your convenience. Thanks @benjamn!

**Comment by bentron2000** [comment]
I also did the comparison between `@apollo/client@beta` (3) and `@apollo/client@3.7.0-beta.0` and can confirm that beta.3 works where the beta.0 immediately has the original issue.
Seems fixed to me.
Thank you!

**Comment by benjamn** [comment]
Thanks for the confirmations everyone!

This should now be fixed if you run `npm i @apollo/client@latest` to get version 3.6.7 (or later).

**Comment by zuspan** [comment]
I'm still having this issue with queries hanging on pending. The request is made, the payload sent, the server returns the response, but the browser still shows it as pending.

I have tried a direct query using client, `the` `useQuery` hook and the `useLazyQuery` hook - all the same issue.

@apollo/client 3.6.9
node 16.16.0

is anyone else still seeing this or have a solution?
