### ISSUE TITLE
Watch queries are stuck in `loading: true, partial: true` when `notifyOnNetworkStatusChange` is enabled

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [apollographql/apollo-client#9845]
When `notifyOnNetworkStatusChange` is enabled some watchQueries get stuck in `loading: true, partial: true` after calling `reobserve`/`setVariables` even if the underlying network request has already returned a successful result.

In particular, this bug happens when a reobserved query returns the same data with the new variables as before, or when the query is simply refreshed.

```
1: loading: false, data           ->   isDifferentFromLastResult=true, savedAsLastResult=true
2: loading: true, partial: true   ->   isDifferentFromLastResult=true, savedAsLastResult=false
3: loading: false, data           ->   isDifferentFromLastResult=false, savedAsLastResult=false, suppressed
```

Related to #9367

Proposed fix in #9844

Aside: notice also that apollo-client is returning `partial: true` even if `returnPartialData` is disabled when `notifyOnNetworkStatusChange` is enabled.

**Intended outcome:**
I would expect ObservableQuery to always report `loading: false` when a network request finishes. Also I would expect apollo client to never `loading: true` open forever.

**Actual outcome:**

ObservableQuery supresses result with `loading: false` because data is the same as `ObservableQuery.last.result`. But `loading: true, partial: true, data: undefined` was not saved as `ObservableQuery.last.result`.

**How to reproduce the issue:**

See test added in pull request #9844

**Versions**

apollo client 3.6.8

**Comment by fmorenodesigns** [comment]
At risk of this being unrelated (my apologies in advance if it isn't the same thing), I'd like to add that this also happens on `fetchMore`, under similar circumstances, i.e.:

> this bug happens when a reobserved query returns the same data with the new variables as before

We have a case where we are using the `InMemoryCache` feature to make pagination. We've noticed that after upgrading to 3.6.0, if the `incoming` page is empty, i.e. the merged result is the `existing` page, then the `loading` state is not updated even though the network connection has completed successfully.

**Comment by bignimbus** [comment]
Hi all, I'm doing some housekeeping and found this issue. It appears this was resolved in #10105 so I'll close this.  Thanks a bunch!

**Comment by fmorenodesigns** [comment]
Thank you for the update on the issue 🙌 
Though I must say that I've just tested this in version 3.7.7 and the problem persists.

**Comment by phryneas** [comment]
@fmorenodesigns since the original issue added a test that is now successful, it seems that you have a different issue.  
Could you please open a new issue and provide some kind of reproduction or test case?
